// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

import {Script, console2} from "forge-std/Script.sol";
import {ShieldedPool} from "../src/ShieldedPool.sol";
import {Verifier} from "../src/Verifier.sol";
import {AllowlistGate} from "../src/AllowlistGate.sol";
import {IHasher} from "../src/interfaces/IHasher.sol";
import {IVerifier} from "../src/interfaces/IVerifier.sol";
import {IComplianceGate} from "../src/interfaces/IComplianceGate.sol";

/// Deploys the full stack: Poseidon hasher (from generated bytecode), Groth16
/// verifier, an allowlist compliance gate, and the pool.
///
///   env:
///     PRIVATE_KEY     deployer key
///     DENOMINATION    wei per note          (default 1 ether)
///     LEVELS          merkle tree depth     (default 20, must match the circuit)
///     ENABLE_GATE     "true" to screen deposits via AllowlistGate (default true)
///
///   forge script script/Deploy.s.sol --rpc-url mainnet --broadcast
contract Deploy is Script {
    function run() external {
        uint256 pk = vm.envUint("PRIVATE_KEY");
        uint256 denomination = vm.envOr("DENOMINATION", uint256(1 ether));
        uint32 levels = uint32(vm.envOr("LEVELS", uint256(20)));
        bool enableGate = vm.envOr("ENABLE_GATE", true);
        address deployer = vm.addr(pk);

        vm.startBroadcast(pk);

        address hasher = _deployHasher();
        Verifier verifier = new Verifier();

        IComplianceGate gate = IComplianceGate(address(0));
        if (enableGate) {
            gate = IComplianceGate(address(new AllowlistGate(deployer)));
        }

        ShieldedPool pool = new ShieldedPool(
            IVerifier(address(verifier)), IHasher(hasher), denomination, levels, gate, deployer
        );

        vm.stopBroadcast();

        console2.log("Hasher    :", hasher);
        console2.log("Verifier  :", address(verifier));
        console2.log("Gate      :", address(gate));
        console2.log("Pool      :", address(pool));
        console2.log("Denomination (wei):", denomination);
    }

    function _deployHasher() internal returns (address h) {
        bytes memory bytecode = vm.parseBytes(vm.trim(vm.readFile("build/PoseidonT3.bytecode")));
        assembly {
            h := create(0, add(bytecode, 0x20), mload(bytecode))
        }
        require(h != address(0), "hasher deploy failed");
    }
}
