// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @notice On-chain Poseidon(2) hasher. The implementation is deployed from
/// bytecode generated by circomlibjs (`poseidonContract.createCode(2)`) so that
/// it is bit-for-bit identical to the Poseidon used inside the circuit.
interface IHasher {
    function poseidon(uint256[2] calldata input) external pure returns (uint256);
}
