[workspace]
resolver = "2"
members = ["token", "factory", "deploy"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/opengrid1/launchpad"

[workspace.dependencies]
near-sdk = "5.29"
near-contract-standards = "5.29"
uint = { version = "0.10", default-features = false }

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true
