import { chromium, devices } from 'playwright'
const browser = await chromium.launch()
const d = await browser.newContext({ viewport: { width: 1440, height: 1000 }, ignoreHTTPSErrors: true })
const p = await d.newPage()
p.on('pageerror', e => console.log('ERR', String(e).slice(0,160)))
await p.goto('http://localhost:4207/#/', { waitUntil: 'domcontentloaded', timeout: 30000 })
await p.waitForTimeout(8000)
await p.screenshot({ path: '/tmp/hero-d.png' })
const m = await browser.newContext({ ...devices['iPhone 13'], ignoreHTTPSErrors: true })
const pm = await m.newPage()
await pm.goto('http://localhost:4207/#/', { waitUntil: 'domcontentloaded', timeout: 30000 })
await pm.waitForTimeout(7000)
await pm.screenshot({ path: '/tmp/hero-m.png' })
await browser.close()
console.log('done')
