import { chromium, devices } from 'playwright'
const browser = await chromium.launch()
const d = await browser.newContext({ viewport: { width: 1440, height: 1000 }, ignoreHTTPSErrors: true })
const p = await d.newPage()
await p.goto('http://localhost:4191/#/t/0x8960bE42d9dEEb973AB6e2DCa837B3bD78c9d5bD', { waitUntil: 'domcontentloaded', timeout: 30000 })
await p.waitForTimeout(5000)
await p.screenshot({ path: '/tmp/ov-desk.png' })
const m = await browser.newContext({ ...devices['iPhone 13'], ignoreHTTPSErrors: true })
const pm = await m.newPage()
await pm.goto('http://localhost:4191/#/t/0x8960bE42d9dEEb973AB6e2DCa837B3bD78c9d5bD', { waitUntil: 'domcontentloaded', timeout: 30000 })
await pm.waitForTimeout(5000)
await pm.screenshot({ path: '/tmp/ov-mob.png' })
await browser.close()
console.log('done')
