import { chromium, devices } from 'playwright'
const browser = await chromium.launch()
const d = await browser.newContext({ viewport: { width: 1440, height: 900 }, ignoreHTTPSErrors: true })
const p1 = await d.newPage()
p1.on('pageerror', (e) => console.log('pageerror:', String(e).slice(0, 200)))
const r = await p1.goto('http://localhost:4175/#/', { waitUntil: 'networkidle', timeout: 30000 })
console.log('status', r?.status())
await p1.waitForTimeout(5000)
await p1.screenshot({ path: '/tmp/final-board.png' })
await p1.goto('http://localhost:4175/#/launch', { waitUntil: 'networkidle' })
await p1.waitForTimeout(1500)
await p1.screenshot({ path: '/tmp/final-launch.png' })
const m = await browser.newContext({ ...devices['iPhone 13'], ignoreHTTPSErrors: true })
const p2 = await m.newPage()
await p2.goto('http://localhost:4175/#/', { waitUntil: 'networkidle', timeout: 30000 })
await p2.waitForTimeout(4000)
await p2.screenshot({ path: '/tmp/final-mobile.png' })
await browser.close()
console.log('done')
