/* interface languages: English, Simplified Chinese, Turkish (same three as the reference) */
const LANGS=[['en','English','EN'],['zh','Simplified Chinese','ZH'],['tr','Turkish','TR']];
const DICT={
zh:{
 'Dashboard':'仪表盘','Profile':'个人主页','Leaderboard':'排行榜','Docs':'文档','Search by name, symbol, or address':'按名称、代码或地址搜索','Launch Token':'发行代币','Connect Wallet':'连接钱包','Connect':'连接','History':'历史','New':'最新','Search':'搜索','Menu':'菜单','Developers':'开发者','Contract addresses':'合约地址','Products':'产品','Current':'当前',
 'Memecoins that pay holders in stocks':'向持有者支付股票的迷因币','Top 5 traders paid every 3 days':'每 3 天奖励前 5 名交易者','How launches, rewards and fees work':'发行、奖励与费用说明','Ink explorer':'Ink 浏览器','Verified contracts and transactions':'已验证合约与交易',
 'Launchpad':'发射台','Give your community something to call its own. Launch':'给你的社区一个属于自己的东西。在 Ink 上发行','memecoins':'迷因币','on':'，部署于','Ink':'Ink','that pay holders in':'，并向持有者支付','stocks':'股票',
 'Launch a token':'发行代币','Explore feed':'浏览列表','Tokens launched':'已发行代币','Traders':'交易者','Lifetime volume':'累计交易量','Paid to holders':'已支付给持有者','Paid to creators':'已支付给创建者','Highest market cap':'最高市值','Trending now':'当前热门','See all':'查看全部',
 'All':'全部','Multi-stock':'多股票','🔥 Trending':'🔥 热门','⚡ Vol 24h':'⚡ 24h 成交量','🌱 New':'🌱 最新','💧 Liquidity':'💧 流动性','All assets':'全部资产','Token':'代币','Market cap':'市值','Liquidity':'流动性','Volume 24h':'24h 成交量','Rewards 24h':'24h 奖励','Holders':'持有者','Price':'价格','Trade':'交易','Load more':'加载更多','Vol 24h':'24h 成交量','NEW':'新',
 'All tokens':'全部代币','Warning':'警告','Tokens launched here cannot mint more supply, pause or freeze trading, or remove the seeded liquidity. Always check holders, pool liquidity and a live sell quote before buying. Copycats may exist here; external honeypots may imitate legitimate launches.':'在此发行的代币无法增发、暂停或冻结交易，也无法撤走初始流动性。购买前请务必查看持有者、池子流动性和实时卖出报价。可能存在仿冒币；外部貔貅盘可能模仿正规发行。','DYOR!':'自行研究！','Refer & earn':'推荐赚取','Immutable':'不可更改','ETH pair':'ETH 交易对',
 'Token price':'代币价格','Pool liquidity':'池子流动性','Total supply':'总供应量','no mint · no tax':'无增发 · 无税','Info':'信息','Creator':'创建者','Created':'创建时间','Trading fee':'交易手续费','Creator revenue':'创建者收入','Holder rewards':'持有者奖励','Protocol revenue':'协议收入','(3 days ago)':'（3 天前）',
 'Transactions':'交易记录','Buy':'买入','Sell':'卖出','Rewards':'奖励','Top traders':'顶级交易者','Updates':'动态','Time':'时间','Type':'类型','Amount':'数量','Value':'价值','Fee':'手续费','Wallet':'钱包','Tx':'交易','Load more transactions':'加载更多交易','No updates from the creator yet.':'创建者暂无动态。',
 'Disclosures':'披露','Locked liquidity and limited control':'流动性锁定与有限控制','No reserved supply':'无预留供应','Anti-sniping protection':'防狙击保护','Fee split':'手续费分配',
 'Swap':'兑换','Auto':'自动','You pay':'支付','You receive':'收到','Max Slippage':'最大滑点','Trade details':'交易详情','Minimum received':'最少收到','Trade fees':'交易手续费','Network fees':'网络费用','Price impact':'价格影响','Route':'路径','Need more advanced trading features?':'需要更高级的交易功能？','Your position':'你的持仓','Avg entry':'平均成本','Unrealized PnL':'未实现盈亏','Stock rewards pending':'待领取股票奖励','Claim basket':'领取股票篮子','Claim as ETH':'以 ETH 领取','Balance:':'余额：','MAX':'最大',
 'Connect wallet':'连接钱包','Connect to Ink (chain 57073) to trade and claim rewards':'连接到 Ink（链 ID 57073）以交易和领取奖励','Browser extension':'浏览器扩展','Scan with your phone':'用手机扫码','Language':'语言','Choose the interface language':'选择界面语言','Network':'网络','Trending':'热门','No tokens match.':'没有匹配的代币。',
 'Trader leaderboard':'交易者排行榜','PnL board':'盈亏榜','Volume board':'成交量榜','How payouts work':'奖励规则','Prize pool':'奖池','Pays out in':'结算倒计时','Traders this epoch':'本周期交易者','How it works':'规则说明','Launch a token':'发行代币','Preview':'预览','Deploy':'部署','Name':'名称','Ticker':'代码','Logo':'图标','Description':'描述','Website':'网站','Rewards basket':'奖励篮子','Review & deploy':'检查并部署','Identity':'基本信息','Holdings':'持仓','Created':'已创建','Activity':'活动','Claim all rewards':'领取全部奖励','Claim':'领取','Connect your wallet':'连接你的钱包','See your holdings, stock rewards, creator fees and leaderboard payouts in one place.':'在一个地方查看你的持仓、股票奖励、创建者收入和排行榜奖励。',
},
tr:{
 'Dashboard':'Panel','Profile':'Profil','Leaderboard':'Liderlik tablosu','Docs':'Dokümanlar','Search by name, symbol, or address':'Ad, sembol veya adrese göre ara','Launch Token':'Token Başlat','Connect Wallet':'Cüzdan Bağla','Connect':'Bağlan','History':'Geçmiş','New':'Yeni','Search':'Ara','Menu':'Menü','Developers':'Geliştiriciler','Contract addresses':'Kontrat adresleri','Products':'Ürünler','Current':'Mevcut',
 'Memecoins that pay holders in stocks':'Sahiplerine hisse ödeyen memecoinler','Top 5 traders paid every 3 days':'Her 3 günde ilk 5 trader ödüllendirilir','How launches, rewards and fees work':'Başlatma, ödüller ve ücretler','Ink explorer':'Ink gezgini','Verified contracts and transactions':'Doğrulanmış kontratlar ve işlemler',
 'Launchpad':'Launchpad','Give your community something to call its own. Launch':'Topluluğuna kendine ait bir şey ver. Ink üzerinde','memecoins':'memecoinler','on':'başlat;','Ink':'Ink','that pay holders in':'sahiplerine','stocks':'hisse',
 'Launch a token':'Token başlat','Explore feed':'Akışı keşfet','Tokens launched':'Başlatılan token','Traders':'Trader','Lifetime volume':'Toplam hacim','Paid to holders':'Sahiplere ödenen','Paid to creators':'Yaratıcılara ödenen','Highest market cap':'En yüksek piyasa değeri','Trending now':'Şu an trend','See all':'Tümünü gör',
 'All':'Tümü','Multi-stock':'Çoklu hisse','🔥 Trending':'🔥 Trend','⚡ Vol 24h':'⚡ Hacim 24s','🌱 New':'🌱 Yeni','💧 Liquidity':'💧 Likidite','All assets':'Tüm varlıklar','Token':'Token','Market cap':'Piyasa değeri','Liquidity':'Likidite','Volume 24h':'Hacim 24s','Rewards 24h':'Ödül 24s','Holders':'Sahipler','Price':'Fiyat','Trade':'İşlem','Load more':'Daha fazla yükle','Vol 24h':'Hacim 24s','NEW':'YENİ',
 'All tokens':'Tüm tokenler','Warning':'Uyarı','Tokens launched here cannot mint more supply, pause or freeze trading, or remove the seeded liquidity. Always check holders, pool liquidity and a live sell quote before buying. Copycats may exist here; external honeypots may imitate legitimate launches.':'Burada başlatılan tokenler ek arz basamaz, işlemleri duraklatamaz veya donduramaz, başlangıç likiditesini çekemez. Almadan önce sahipleri, havuz likiditesini ve canlı satış teklifini mutlaka kontrol et. Taklitler olabilir; dış honeypotlar meşru başlatmaları taklit edebilir.','DYOR!':'Kendi araştırmanı yap!','Refer & earn':'Öner ve kazan','Immutable':'Değiştirilemez','ETH pair':'ETH paritesi',
 'Token price':'Token fiyatı','Pool liquidity':'Havuz likiditesi','Total supply':'Toplam arz','no mint · no tax':'basım yok · vergi yok','Info':'Bilgi','Creator':'Yaratıcı','Created':'Oluşturulma','Trading fee':'İşlem ücreti','Creator revenue':'Yaratıcı geliri','Holder rewards':'Sahip ödülleri','Protocol revenue':'Protokol geliri','(3 days ago)':'(3 gün önce)',
 'Transactions':'İşlemler','Buy':'Al','Sell':'Sat','Rewards':'Ödüller','Top traders':'En iyi traderlar','Updates':'Güncellemeler','Time':'Zaman','Type':'Tür','Amount':'Miktar','Value':'Değer','Fee':'Ücret','Wallet':'Cüzdan','Tx':'İşlem','Load more transactions':'Daha fazla işlem yükle','No updates from the creator yet.':'Yaratıcıdan henüz güncelleme yok.',
 'Disclosures':'Açıklamalar','Locked liquidity and limited control':'Kilitli likidite ve sınırlı kontrol','No reserved supply':'Ayrılmış arz yok','Anti-sniping protection':'Snipe koruması','Fee split':'Ücret dağılımı',
 'Swap':'Takas','Auto':'Otomatik','You pay':'Ödersin','You receive':'Alırsın','Max Slippage':'Maks. kayma','Trade details':'İşlem detayları','Minimum received':'Minimum alınan','Trade fees':'İşlem ücretleri','Network fees':'Ağ ücretleri','Price impact':'Fiyat etkisi','Route':'Rota','Need more advanced trading features?':'Daha gelişmiş işlem özellikleri mi lazım?','Your position':'Pozisyonun','Avg entry':'Ort. giriş','Unrealized PnL':'Gerçekleşmemiş K/Z','Stock rewards pending':'Bekleyen hisse ödülü','Claim basket':'Sepeti al','Claim as ETH':'ETH olarak al','Balance:':'Bakiye:','MAX':'MAKS',
 'Connect wallet':'Cüzdan bağla','Connect to Ink (chain 57073) to trade and claim rewards':'İşlem yapmak ve ödül almak için Ink (zincir 57073) ağına bağlan','Browser extension':'Tarayıcı eklentisi','Scan with your phone':'Telefonunla tara','Language':'Dil','Choose the interface language':'Arayüz dilini seç','Network':'Ağ','Trending':'Trend','No tokens match.':'Eşleşen token yok.',
 'Trader leaderboard':'Trader liderlik tablosu','PnL board':'K/Z tablosu','Volume board':'Hacim tablosu','How payouts work':'Ödemeler nasıl işler','Prize pool':'Ödül havuzu','Pays out in':'Ödeme süresi','Traders this epoch':'Bu dönem trader','How it works':'Nasıl çalışır','Preview':'Önizleme','Deploy':'Dağıt','Name':'Ad','Ticker':'Sembol','Logo':'Logo','Description':'Açıklama','Website':'Web sitesi','Rewards basket':'Ödül sepeti','Review & deploy':'İncele ve dağıt','Identity':'Kimlik','Holdings':'Varlıklar','Activity':'Etkinlik','Claim all rewards':'Tüm ödülleri al','Claim':'Al','Connect your wallet':'Cüzdanını bağla','See your holdings, stock rewards, creator fees and leaderboard payouts in one place.':'Varlıklarını, hisse ödüllerini, yaratıcı ücretlerini ve liderlik ödemelerini tek yerde gör.',
}};
const RX={
 zh:[[/^(\d+)s ago$/,'$1 秒前'],[/^(\d+)m ago$/,'$1 分钟前'],[/^(\d+)h ago$/,'$1 小时前'],[/^(\d+)d ago$/,'$1 天前'],[/^yesterday$/,'昨天'],[/^approx (.*)$/,'约 $1'],[/^Fee (.*)$/,'手续费 $1'],[/^Balance: (.*)$/,'余额：$1'],[/^Buy (\S+)$/,'买入 $1'],[/^Sell (\S+)$/,'卖出 $1'],[/^(\d+) · Identity$/,'$1 · 基本信息'],[/^(\d+) · Rewards basket$/,'$1 · 奖励篮子'],[/^(\d+) · Review & deploy$/,'$1 · 检查并部署']],
 tr:[[/^(\d+)s ago$/,'$1 sn önce'],[/^(\d+)m ago$/,'$1 dk önce'],[/^(\d+)h ago$/,'$1 sa önce'],[/^(\d+)d ago$/,'$1 g önce'],[/^yesterday$/,'dün'],[/^approx (.*)$/,'yaklaşık $1'],[/^Fee (.*)$/,'Ücret $1'],[/^Balance: (.*)$/,'Bakiye: $1'],[/^Buy (\S+)$/,'$1 Al'],[/^Sell (\S+)$/,'$1 Sat'],[/^(\d+) · Identity$/,'$1 · Kimlik'],[/^(\d+) · Rewards basket$/,'$1 · Ödül sepeti'],[/^(\d+) · Review & deploy$/,'$1 · İncele ve dağıt']],
};
let LANG='en'; try{ LANG=localStorage.getItem('lang')||'en'; }catch{}
function trText(en){ if(LANG==='en') return en; const key=en.trim(); if(!key) return en; const d=DICT[LANG]; let out=null; if(d[key]!=null) out=d[key]; else for(const [rx,rep] of RX[LANG]){ if(rx.test(key)){ out=key.replace(rx,rep); break; } } if(out==null) return en; return en.replace(key,out); }
function applyLang(root){ root=root||document.body; const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode:n=>{ const p=n.parentElement; if(!p||['SCRIPT','STYLE','INPUT','TEXTAREA'].includes(p.tagName)) return NodeFilter.FILTER_REJECT; return NodeFilter.FILTER_ACCEPT; }}); const nodes=[]; while(w.nextNode()) nodes.push(w.currentNode);
  for(const n of nodes){ if(n.__en==null) n.__en=n.nodeValue; const t=trText(n.__en); if(n.nodeValue!==t) n.nodeValue=t; }
  root.querySelectorAll('input[placeholder]').forEach(i=>{ if(i.__en==null) i.__en=i.placeholder; const t=trText(i.__en); if(i.placeholder!==t) i.placeholder=t; });
  document.documentElement.lang=LANG==='zh'?'zh-CN':LANG; const lb=document.querySelector('header button[aria-label^="Language"] span'); if(lb) lb.textContent=LANGS.find(l=>l[0]===LANG)[2]; }
function setLang(code){ LANG=code; try{ localStorage.setItem('lang',code); }catch{} applyLang(); }
let langTimer=null; document.addEventListener('DOMContentLoaded',()=>{ applyLang(); new MutationObserver(()=>{ if(LANG==='en') return; clearTimeout(langTimer); langTimer=setTimeout(()=>applyLang(),30); }).observe(document.body,{childList:true,subtree:true}); });
