/* behaviour for launch / profile / leaderboard / docs / admin */
const stockAv=(s,sz)=>`<span class="relative flex shrink-0 overflow-hidden rounded-full ring-1 ring-inset ring-text-primary/10 ${sz}" style="background:${STOCK_COLOR[s]}"><span class="absolute inset-0 flex items-center justify-center font-bold text-white">${s[0]}</span></span>`;
const stockTag=s=>`<span class="inline-flex h-6 items-center gap-1.5 rounded-full px-2.5 text-xs font-semibold leading-none md:text-[11px] bg-bg-input text-text-secondary" title="${STOCK_NAME[s]}">${stockAv(s,'-ml-1 size-4.5')}${s}</span>`;
const tokAv=(x,sz,extra='')=>`<span class="relative flex shrink-0 overflow-hidden rounded-md ring-1 ring-inset ring-text-primary/10 ${sz} ${extra}" style="background:${x.c}"><span class="absolute inset-0 flex items-center justify-center rounded-md font-bold text-text-primary">${x.t[0]}</span></span>`;
const setTab=(sel,on,offCls='text-text-muted hover:text-text-secondary')=>$$(sel).forEach(b=>{ b.className=b.className.replace(/ text-text-primary| text-text-muted hover:text-text-secondary/g,'')+(b===on?' text-text-primary':' '+offCls); });

/* ======================= LAUNCH ======================= */
function initLaunch(){
  const g=id=>document.getElementById(id); const TAKEN=new Set(TOK.map(x=>x.t)); let basket=['NVDAx','SPYx'], logoURL=null; const LOGOS=['pLogo','pLogo2','pLogo3','pLogo4'];
  const paint=()=>{ const t=(g('fTick').value.trim()||'TKN').toUpperCase(); LOGOS.forEach(i=>{ const el=g(i); const inner=el.querySelector('span'); if(logoURL){ el.style.background='none'; inner.innerHTML=`<img src="${logoURL}" alt="" class="absolute inset-0 size-full rounded-md object-cover">`; } else { inner.textContent=t.slice(0,2); } }); };
  function val1(){ const n=g('fName').value.trim(), t=g('fTick').value.trim().toUpperCase(); let ok=true; g('nMsg').textContent=n?'':'Name is required'; if(!n) ok=false;
    if(!/^[A-Z0-9]{2,10}$/.test(t)){ g('tMsg').className='text-[12px] font-medium text-error'; g('tMsg').textContent='Ticker: 2–10 characters, A–Z and 0–9'; ok=false; }
    else if(TAKEN.has(t)){ g('tMsg').className='text-[12px] font-medium text-error'; g('tMsg').textContent='$'+t+' is already taken'; ok=false; }
    else { g('tMsg').className='text-[12px] font-medium text-success'; g('tMsg').textContent='$'+t+' is available'; } return ok; }
  function val2(){ const c=parseFloat(g('fCommit').value)||0; const ok=c>=0&&c<=0.5; g('cMsg').textContent=ok?'':'First buy must be between 0 and 0.5 ETH'; g('pkMsg').textContent=basket.length?'':'Pick at least one stock'; return ok&&basket.length>0; }
  function sync(){ const n=g('fName').value.trim()||'Untitled', t=(g('fTick').value.trim()||'TKN').toUpperCase(), d=g('fDesc').value, c=parseFloat(g('fCommit').value)||0;
    g('nC').textContent=g('fName').value.length+' / 32'; g('tC').textContent=t.length+' / 10'; g('dC').textContent=d.length+' / 280'; paint();
    g('pName').textContent=n; g('rName2').textContent=n; g('dName').textContent=n; g('pTick').textContent=t; g('rTick2').textContent=t; g('rDesc').textContent=d;
    const links=[g('fWeb').value,g('fX').value,g('fTg').value].filter(Boolean).map(s=>s.replace(/^https?:\/\//,'')); g('rLinks').textContent=links.join(' · ')||'no links';
    g('rCommit').textContent=c+' ETH'; g('rTotal').textContent=(c+0.000002).toFixed(4)+' ETH'; g('fbTxt').textContent=c+' ETH'; const out=c/(2+c)*950e6; g('fbOut').textContent=fmtAmt(out); g('rOut').textContent=fmtAmt(out)+' tokens'; g('dBuy').textContent=fmtAmt(out)+' tokens';
    const tags=basket.map(stockTag).join(''); g('pBasket').innerHTML=tags; g('dBasket').innerHTML=tags; g('rTags').innerHTML=tags+`<span class="inline-flex h-6 items-center gap-1.5 rounded-full px-2.5 text-xs font-semibold leading-none md:text-[11px] bg-success-soft text-success">Immutable</span>`; g('pkC').textContent=basket.length+' / 4 selected'; }
  function drawPick(){ g('pick').innerHTML=STOCKS.map(s=>{ const on=basket.includes(s[0]); const off=!on&&basket.length>=4; return `<button type="button" class="flex items-center gap-3 rounded-2xl bg-bg-card px-3 py-2.5 text-left transition-colors hover:bg-bg-elevated${off?' opacity-50':''}" data-s="${s[0]}" style="${on?'box-shadow:inset 0 0 0 1.5px var(--color-accent)':''}">${stockAv(s[0],'size-8')}<span class="min-w-0 flex-1"><span class="block truncate text-sm font-semibold text-text-primary">${s[0]}</span><span class="block truncate text-[12px] text-text-muted">${s[1]} · liq ${fmtUsd(s[3])}</span></span>${on?ic('check','size-4 text-accent'):''}</button>`; }).join(''); }
  g('pick').addEventListener('click',e=>{ const b=e.target.closest('[data-s]'); if(!b||b.classList.contains('opacity-50')) return; const s=b.dataset.s; basket=basket.includes(s)?basket.filter(x=>x!==s):[...basket,s]; drawPick(); sync(); val2(); }); drawPick();
  ['fName','fTick','fDesc','fCommit','fWeb','fX','fTg'].forEach(i=>g(i).addEventListener('input',()=>{ sync(); if(i==='fName'||i==='fTick') val1(); if(i==='fCommit') val2(); }));
  let cur=1, maxDone=1;
  function go(s){ if(s>cur){ if(cur===1&&!val1()) return; if(cur===2&&!val2()) return; } cur=s; maxDone=Math.max(maxDone,s);
    $$('[data-wiz]').forEach(x=>{ const on=x.dataset.wiz===String(s); x.classList.toggle('hidden',!on); x.classList.toggle('flex',on); });
    $$('#steps [data-step]').forEach(x=>{ const k=+x.dataset.step; const base=x.className.replace(/ bg-accent text-accent-ink| text-text-secondary hover:text-text-primary/g,''); x.className=base+(k===s?' bg-accent text-accent-ink':' text-text-secondary hover:text-text-primary'); x.disabled=k>maxDone; });
    $('main').scrollTo({top:0,behavior:'smooth'}); }
  $$('[data-next]').forEach(b=>b.onclick=()=>go(+b.dataset.next)); $$('#steps [data-step]').forEach(x=>x.onclick=()=>{ if(+x.dataset.step<=maxDone) go(+x.dataset.step); });
  function loadLogo(file){ if(!file||!file.type.startsWith('image/')){ g('logoMsg').textContent='Please choose an image file.'; return; } if(file.size>1024*1024){ g('logoMsg').textContent='Too big, max 1 MB.'; return; }
    const img=new Image(); img.onload=()=>{ const c=document.createElement('canvas'); c.width=c.height=256; const x=c.getContext('2d'); const s=Math.min(img.width,img.height); x.drawImage(img,(img.width-s)/2,(img.height-s)/2,s,s,0,0,256,256); logoURL=c.toDataURL('image/webp',0.85); g('logoMsg').textContent=file.name+' · '+Math.round(logoURL.length*0.75/1024)+' KB as webp · ready'; sync(); }; img.src=URL.createObjectURL(file); }
  g('fLogo').addEventListener('change',e=>loadLogo(e.target.files[0])); const dz=g('drop'); ['dragenter','dragover'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault(); dz.style.borderColor='var(--color-accent)';})); ['dragleave','drop'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault(); dz.style.borderColor='';})); dz.addEventListener('drop',e=>loadLogo(e.dataTransfer.files[0]));
  g('deploy').onclick=()=>{ if(!W.connected) return openConnect(); if(!g('fAck').checked){ g('aMsg').textContent='Tick the box to continue.'; return; } g('aMsg').textContent=''; const b=g('deploy'); b.disabled=true; b.textContent='Confirm in wallet…'; setTimeout(()=>{ b.textContent='Deploying…'; },900);
    setTimeout(()=>{ $$('[data-wiz]').forEach(x=>{ const on=x.dataset.wiz==='done'; x.classList.toggle('hidden',!on); x.classList.toggle('flex',on); }); b.disabled=false; b.innerHTML=ic('rocket')+'Deploy'; toast((g('fName').value||'Token')+' deployed on Ink'); $('main').scrollTo({top:0,behavior:'smooth'}); },2200); };
  g('shareX').onclick=()=>{ const t=g('fTick').value.trim().toUpperCase(); open('https://x.com/intent/tweet?text='+encodeURIComponent('$'+t+' is live on Batch (Ink). LP locked forever. Holders earn '+basket.join(' + ')+' on every trade.')); };
  sync();
}

/* ======================= LEADERBOARD ======================= */
function initBoard(){
  const pool=0.93; const payout=i=>i<5?pool*LB_TIER[i]/100:0;
  function draw(kind){ const rows=kind==='pnl'?LB_PNL:LB_VOL; setTab('#btabs [data-board]',$(`#btabs [data-board="${kind}"]`));
    $('#podium').innerHTML=rows.slice(0,3).map((r,i)=>`<div class="flex items-center gap-3 rounded-2xl px-4 py-3 ${r[2]?'border border-accent/20 bg-accent/10':'bg-bg-input'}">${rank(i)}<div class="min-w-0 flex-1"><div class="flex items-center gap-2"><span class="truncate font-mono text-sm font-semibold text-text-primary">${r[0]}</span>${r[2]?'<span class="inline-flex h-5 items-center rounded-full bg-accent px-2 text-[11px] font-semibold text-accent-ink">YOU</span>':''}</div><div class="mt-1 text-xs text-text-muted">${kind==='pnl'?'realized PnL':'fees paid · volume '+(r[1]*50).toFixed(0)+' ETH'}</div></div><div class="shrink-0 text-right"><div class="text-[15px] font-semibold tabular-nums ${kind==='pnl'?'text-success':'text-text-primary'}">${kind==='pnl'?'+':''}${r[1].toFixed(2)} ETH</div><div class="mt-0.5 text-xs tabular-nums text-text-muted">payout ${payout(i).toFixed(3)} ETH</div></div></div>`).join('');
    const th=(t,w,a)=>`<th class="h-12 whitespace-nowrap bg-bg-input px-3 align-middle font-normal first:rounded-l-2xl first:pl-4 last:rounded-r-2xl last:pr-5 w-[${w}] text-${a}">${t}</th>`;
    $('#bth').innerHTML=th('#','7%','left')+th('Wallet','15%','left')+th(kind==='pnl'?'Realized PnL':'Fees paid','14%','right')+th('Trades','12%','right')+th('Best token','15%','right')+th('Payout','13%','right');
    $('#btb').innerHTML=rows.map((r,i)=>{ const x=TOK[i%TOK.length]; return `<tr class="h-[4.5rem] text-text-primary${r[2]?' bg-accent/10':''}${i>=5?' opacity-60':''}">${tdiv('whitespace-nowrap px-4 py-3 align-middle',rank(i,true))}${tdiv('px-4 py-3 align-middle',wlink(r[0])+(r[2]?tagS('YOU'):''))}${tdiv('px-4 py-3 align-middle text-right tabular-nums','<span class="block font-medium '+(kind==='pnl'?'text-success':'text-text-primary')+'">'+(kind==='pnl'?'+':'')+r[1].toFixed(2)+' ETH</span>')}${tdiv('px-4 py-3 align-middle text-right tabular-nums',cellR(String(40+Math.floor(rnd()*300))))}${tdiv('px-4 py-3 align-middle text-right','<span class="inline-flex items-center justify-end gap-2">'+tokAv(x,'size-6 text-[10px]')+'<span class="font-medium">$'+x.t+'</span></span>')}${tdiv('px-4 py-3 align-middle text-right tabular-nums',i<5?cellR(payout(i).toFixed(3)+' ETH'):'<span class="block text-text-muted">—</span>')}</tr>`; }).join('')+`<tr><td colspan="6" class="px-4 py-4 text-center text-xs text-text-muted">only the top 5 are paid · #6 needs +0.15 ETH to get in</td></tr>`;
    $('#bmob').innerHTML=rows.map((r,i)=>`<div class="flex items-center gap-3 border-b border-border-default py-3 last:border-b-0${i>=5?' opacity-60':''}">${rank(i,true)}<div class="min-w-0 flex-1"><div class="truncate font-mono text-sm font-semibold text-text-primary">${r[0]}${r[2]?' <span class="text-accent">· you</span>':''}</div><div class="mt-0.5 text-xs text-text-muted">${40+Math.floor(rnd()*300)} trades · best $${TOK[i%TOK.length].t}</div></div><div class="shrink-0 text-right"><div class="text-sm font-semibold tabular-nums ${kind==='pnl'?'text-success':'text-text-primary'}">${kind==='pnl'?'+':''}${r[1].toFixed(2)} ETH</div><div class="mt-0.5 text-xs text-text-muted">${i<5?'payout '+payout(i).toFixed(3)+' ETH':'—'}</div></div></div>`).join(''); }
  $$('#btabs [data-board]').forEach(b=>b.onclick=()=>draw(b.dataset.board)); draw('pnl');
  let ends=LB_ENDS; setInterval(()=>{ ends--; $('#cd').textContent=Math.floor(ends/86400)+'d '+Math.floor(ends%86400/3600)+'h '+Math.floor(ends%3600/60)+'m'; },1000);
  if(!W.connected){ const y=$('#youCard'); y.innerHTML='<div class="flex h-7 items-center"><div class="text-lg font-semibold text-text-primary">Connect to see your rank</div></div><div class="mt-0.5 text-xs font-medium text-accent">Every trade counts, wherever you trade</div>'; y.style.cursor='pointer'; y.onclick=openConnect; }
}

/* ======================= PROFILE ======================= */
function initProfile(){
  const H=[{t:'MOGCAT',n:'Mogcat',c:'#f2a93b',bal:2104320,px:0.000927,avg:0.000352,earned:38.4,pend:21.9},{t:'CPEPE',n:'Cold Pepe',c:'#7fe3d1',bal:180400,px:0.00241,avg:0.00263,earned:12.1,pend:9.3},{t:'WEN',n:'Wen Lambo',c:'#b8c6ff',bal:910000,px:0.000412,avg:0.000301,earned:14.6,pend:8.1},{t:'GRASS',n:'Touch Grass',c:'#a3e68a',bal:52000,px:0.000288,avg:0.000330,earned:2.2,pend:1.9}];
  const bk=t=>BASKETS[t]||['SPYx'];
  const rrow=(av,title,sub,val,btns)=>`<div class="flex min-w-0 items-center gap-3 border-b border-border-default px-4 py-3 last:border-b-0 hover:bg-bg-elevated">${av}<div class="min-w-0 flex-1"><div class="truncate text-sm font-semibold text-text-primary">${title}</div><div class="mt-1 truncate text-xs text-text-muted">${sub}</div></div><div class="hidden shrink-0 text-right sm:block"><div class="text-sm font-semibold tabular-nums text-success">${val}</div></div><div class="flex shrink-0 gap-1.5">${btns}</div></div>`;
  const pb=(t,msg,pri)=>`<button class="inline-flex h-8 cursor-pointer items-center gap-1.5 rounded-full px-3 text-xs font-semibold transition-colors ${pri?'bg-accent text-accent-ink hover:bg-accent-hover':'bg-bg-elevated text-text-primary hover:bg-bg-selector-hover'}" data-toast="${msg}">${t}</button>`;
  $('#rewards').innerHTML=H.map(h=>rrow(tokAv(h,'size-9 text-sm'),h.n+' · $'+h.pend.toFixed(2)+' pending','paid in '+bk(h.t).join(' · ')+' · lifetime $'+h.earned.toFixed(2),'$'+h.pend.toFixed(2),pb('Claim','Claimed $'+h.pend.toFixed(2)+' in '+bk(h.t).join(', '),1)+pb('as ETH','Claimed as ETH')))
    +rrow(`<span class="flex size-9 shrink-0 items-center justify-center rounded-md bg-bg-elevated text-text-primary">${ic('coins')}</span>`,'Creator fees · Mogcat','0.7% of $1.21M 24h volume · lifetime 9.84 ETH','0.22 ETH',pb('Claim','Claimed 0.22 ETH',1))
    +rrow(`<span class="flex size-9 shrink-0 items-center justify-center rounded-md bg-bg-elevated text-text-primary">${ic('trophy')}</span>`,'Leaderboard · epoch 30','#2 PnL last epoch · 25% of 1.07 ETH','0.27 ETH',pb('Claim','Claimed 0.27 ETH',1));
  $('#htb').innerHTML=H.map(h=>{ const v=h.bal*h.px, p=(h.px/h.avg-1)*100; return `<tr class="h-[4.5rem] cursor-pointer text-text-primary hover:bg-bg-elevated" onclick="location.href='token.html'">${tdiv('px-4 py-3 align-middle','<span class="flex items-center gap-3">'+tokAv(h,'size-9 text-sm')+'<span class="min-w-0"><span class="block truncate text-sm font-bold">'+h.t+'</span><span class="block truncate text-xs text-text-muted">'+h.n+'</span></span></span>')}${tdiv('px-4 py-3 align-middle text-right tabular-nums',cellR(fmtAmt(h.bal)))}${tdiv('px-4 py-3 align-middle text-right tabular-nums',cellR(fmtUsd(v),(v/ETH).toFixed(3)+' ETH'))}${tdiv('px-4 py-3 align-middle text-right tabular-nums',cellR('$'+fmtPrice(h.avg)))}${tdiv('px-4 py-3 align-middle text-right tabular-nums','<span class="block font-medium '+(p>=0?'text-success':'text-error')+'">'+(p>=0?'+':'')+p.toFixed(1)+'%</span>')}${tdiv('px-4 py-3 align-middle text-right','<span class="inline-flex justify-end gap-1">'+bk(h.t).map(s=>stockAv(s,'size-5 text-[9px]')).join('')+'</span>')}${tdiv('px-4 py-3 align-middle text-right tabular-nums','<span class="block font-medium text-success">$'+h.pend.toFixed(2)+'</span>')}${tdiv('px-4 py-3 align-middle text-right','<span class="inline-flex gap-1" onclick="event.stopPropagation()">'+pb('50%','Sold 50% '+h.t)+pb('100%','Sold all '+h.t)+'</span>')}</tr>`; }).join('');
  $('#hmob').innerHTML=H.map(h=>{ const v=h.bal*h.px,p=(h.px/h.avg-1)*100; return `<a class="flex items-center gap-3 border-b border-border-default py-3.5 last:border-b-0" href="token.html">${tokAv(h,'size-11 text-sm')}<div class="min-w-0 flex-1"><div class="flex min-w-0 items-center gap-2"><span class="truncate text-sm font-bold text-text-primary">${h.t}</span><span class="truncate text-sm font-medium text-text-muted">${h.n}</span></div><div class="mt-1 flex items-center gap-1.5 text-[13px] leading-none text-text-muted"><span>${fmtAmt(h.bal)}</span><span class="text-text-disabled">·</span><span class="text-success">$${h.pend.toFixed(2)} pending</span></div></div><div class="shrink-0 text-right"><div class="text-[15px] font-medium tabular-nums text-text-primary">${fmtUsd(v)}</div><div class="mt-0.5 text-xs tabular-nums ${p>=0?'text-success':'text-error'}">${p>=0?'+':''}${p.toFixed(1)}%</div></div></a>`; }).join('');
  const x=TOK[0];
  $('#ctb').innerHTML=`<tr class="h-[4.5rem] cursor-pointer text-text-primary hover:bg-bg-elevated" onclick="location.href='token.html'">${tdiv('px-4 py-3 align-middle','<span class="flex items-center gap-3">'+tokAv(x,'size-9 text-sm')+'<span class="min-w-0"><span class="block truncate text-sm font-bold">'+x.t+'</span><span class="block truncate text-xs text-text-muted">'+x.n+'</span></span></span>')}${tdiv('px-4 py-3 align-middle text-right tabular-nums',cellR(fmtUsd(x.mc)))}${tdiv('px-4 py-3 align-middle text-right tabular-nums',cellR(fmtUsd(x.vol)))}${tdiv('px-4 py-3 align-middle text-right tabular-nums',cellR(x.h.toLocaleString()))}${tdiv('px-4 py-3 align-middle text-right tabular-nums',cellR('$53.8K','22.11 ETH lifetime'))}${tdiv('px-4 py-3 align-middle text-right tabular-nums','<span class="block font-medium text-success">0.22 ETH</span>')}${tdiv('px-4 py-3 align-middle text-right','<span class="inline-flex gap-1" onclick="event.stopPropagation()">'+pb('Claim','Claimed 0.22 ETH',1)+pb('Edit','Metadata editor opens in the live build')+'</span>')}</tr>`;
  $('#cmob').innerHTML=`<a class="flex items-center gap-3 py-3.5" href="token.html">${tokAv(x,'size-11 text-sm')}<div class="min-w-0 flex-1"><div class="text-sm font-bold text-text-primary">${x.t}</div><div class="mt-1 text-[13px] leading-none text-text-muted">${fmtUsd(x.mc)} mcap · ${x.h.toLocaleString()} holders</div></div><div class="shrink-0 text-right"><div class="text-[15px] font-medium text-success">0.22 ETH</div><div class="mt-0.5 text-xs text-text-muted">claimable</div></div></a>`;
  const ACT=[['4s ago','Buy','0.1 ETH → 239.1K MOGCAT','text-success'],['2h ago','Claim','$18.40 in NVDAx + SPYx + TSLAx + MSTRx · Mogcat rewards','text-success'],['5h ago','Sell','50% WEN → 0.182 ETH · +0.06 realized','text-error'],['9h ago','Claim as ETH','0.004 ETH · Cold Pepe rewards','text-success'],['yesterday','Leaderboard','Epoch 30 · #2 PnL · 0.27 ETH','text-success'],['2d ago','Launch','Mogcat · $MOGCAT deployed · basket NVDAx SPYx TSLAx MSTRx','text-text-primary']];
  $('#act').innerHTML=ACT.map(a=>`<div class="flex items-center gap-3 border-b border-border-default py-3.5 last:border-b-0"><span class="w-[72px] shrink-0 text-xs text-text-muted">${a[0]}</span><div class="min-w-0 flex-1 text-sm"><span class="font-semibold ${a[3]}">${a[1]}</span> <span class="text-text-secondary">${a[2]}</span></div><a class="inline-flex text-text-muted hover:text-accent" href="https://explorer.inkonchain.com" target="_blank" rel="noopener noreferrer">${ic('ext','size-3.5')}</a></div>`).join('');
  $$('#ptabs [data-ptab]').forEach(b=>b.onclick=()=>{ setTab('#ptabs [data-ptab]',b); $$('#ppanes [data-ppane]').forEach(p=>p.classList.toggle('hidden',p.dataset.ppane!==b.dataset.ptab)); });
  $('#claimAll').onclick=()=>toast('Claimed $41.20 in stocks, 0.22 ETH creator fees and 0.27 ETH leaderboard payout');
  if(!W.connected){ const ov=dialog(dh('Connect to view your profile','Holdings, rewards and leaderboard rank are read from your wallet')+'<div class="db"><button class="opt" id="pc"><span class="ic" style="background:var(--color-accent);color:var(--color-accent-ink)">'+ic('wallet')+'</span><span>Connect wallet<small>MetaMask, Rabby, WalletConnect, Coinbase</small></span></button></div>'); $('#pc',ov).onclick=()=>{ ov.remove(); openConnect(); }; }
}

/* ======================= DOCS ======================= */
function initDocs(){ const links=$$('#toc a'); const main=$('main'); const hs=links.map(a=>$(a.getAttribute('href'))); const io=new IntersectionObserver(es=>{ es.forEach(e=>{ if(e.isIntersecting) links.forEach(a=>a.classList.toggle('on',a.getAttribute('href')==='#'+e.target.id)); }); },{root:main,rootMargin:'-10% 0px -80% 0px'}); hs.forEach(h=>h&&io.observe(h));
  links.forEach(a=>a.onclick=e=>{ e.preventDefault(); const t=$(a.getAttribute('href')); if(t) main.scrollTo({top:t.offsetTop-24,behavior:'smooth'}); history.replaceState(null,'',a.getAttribute('href')); });
  if(location.hash){ const t=$(location.hash); if(t) setTimeout(()=>main.scrollTo({top:t.offsetTop-24}),50); } }

/* ======================= ADMIN ======================= */
function initAdmin(){ $('#qa').innerHTML=STOCKS.map(s=>stockTag(s[0])).join('');
  $('#atb').innerHTML=TOK.map(x=>`<tr class="h-[4.5rem] text-text-primary">${tdiv('px-4 py-3 align-middle','<span class="flex items-center gap-3">'+tokAv(x,'size-9 text-sm')+'<span class="min-w-0"><span class="block truncate text-sm font-bold">'+x.t+'</span><span class="block truncate text-xs text-text-muted">'+x.n+'</span></span></span>')}${tdiv('px-4 py-3 align-middle text-right',x.t==='DEAD'?'<span class="font-medium text-error">yes</span>':'<span class="text-text-muted">no</span>')}${tdiv('px-4 py-3 align-middle text-right tabular-nums',cellR(fmtUsd(x.mc)))}${tdiv('px-4 py-3 align-middle text-right tabular-nums',cellR((x.vol*0.008/ETH).toFixed(3)+' ETH'))}${tdiv('px-4 py-3 align-middle text-right tabular-nums',cellR(fmtUsd(x.liq)))}${tdiv('px-4 py-3 align-middle text-right','<span class="inline-flex gap-1"><button class="adm-btn sm" data-toast="Editor opens in the live build">Edit</button><button class="adm-btn sm" data-toast="Hidden">Hide</button><button class="adm-btn sm" data-toast="Fees pushed">Push fees</button></span>')}</tr>`).join('');
  let e=LB_ENDS; setInterval(()=>{ e--; const c=$('#cd'); if(c) c.textContent=Math.floor(e/86400)+'d '+Math.floor(e%86400/3600)+'h'; },1000);
  $$('[data-toast]').forEach(b=>b.addEventListener('click',()=>toast(b.dataset.toast)));
}

document.addEventListener('DOMContentLoaded',()=>{ if($('#launchPage')) initLaunch(); if($('#boardPage')) initBoard(); if($('#profilePage')) initProfile(); if($('#docsPage')) initDocs(); if($('#adminPage')) initAdmin(); });
