/* behaviour for launch / profile / leaderboard / docs / operator (live data through chain.js) */
const stockAv=(s,sz)=>`<span class="relative flex shrink-0 overflow-hidden rounded-full bg-avatar-gradient ring-1 ring-inset ring-text-primary/10 ${sz}"><span class="absolute inset-0 flex items-center justify-center font-bold text-text-primary">${s[0]}</span><img alt="" class="absolute inset-0 size-full object-cover" src="${pairImg(s)}"></span>`;
const tokAv=(x,sz,extra='')=>`<span class="relative flex shrink-0 overflow-hidden rounded-md bg-avatar-gradient ring-1 ring-inset ring-text-primary/10 ${sz} ${extra}"><span class="absolute inset-0 flex items-center justify-center rounded-md font-bold text-text-primary">${esc(x.t[0])}</span><img alt="" class="absolute inset-0 size-full rounded-md object-cover" src="${x.img||DEF_LOGO}" onerror="this.onerror=null;this.src='${DEF_LOGO}'"></span>`;
const setTab=(sel,on,offCls='text-text-muted hover:text-text-secondary')=>$$(sel).forEach(b=>{ b.className=b.className.replace(/ text-text-primary| text-text-muted hover:text-text-secondary/g,'')+(b===on?' text-text-primary':' '+offCls); });
const pb=(t,act,pri,extra='')=>`<button class="inline-flex h-8 cursor-pointer items-center gap-1.5 rounded-full px-3 text-xs font-semibold transition-colors disabled:opacity-50 ${pri?'bg-accent text-accent-ink hover:bg-accent-hover':'bg-bg-elevated text-text-primary hover:bg-bg-selector-hover'}" data-act="${act}" ${extra}>${t}</button>`;
const rewardsOf=x=>x.rewards?(x.basket.length?x.basket:[x.pair]):[];
async function runTx(btn,fn,okMsg){ const t=btn?btn.textContent:''; if(btn){ btn.disabled=true; btn.textContent='Confirm…'; } try{ await fn(); if(okMsg) toast(okMsg); return true; }catch(e){ toast(errMsg(e),'x'); return false; } finally { if(btn){ btn.disabled=false; btn.textContent=t; } } }

/* ======================= LAUNCH ======================= */
function initLaunch(){
  const g=id=>document.getElementById(id); const TAKEN=new Set((window.CHAIN&&LIVE?CHAIN.tokens():TOK).map(x=>x.t.toUpperCase())); let basket=['NVDAx','SPYx'], logoURL=null, dev=false, pair='ETH', rew=true, busy=false;
  const PAIR_USD={ETH:ETH}; STOCKS.forEach(s=>PAIR_USD[s[0]]=0);
  const PAIRS=[['ETH','Ethereum',ETH_IMG],...STOCKS.filter(s=>!LIVE||STOCK_ADDR[s[0]]).map(x=>[x[0],x[1],STOCK_IMG(x[0])])]; const pairImg2=()=>PAIRS.find(x=>x[0]===pair)[2]; const CAP_USD=3000;
  const pairAddr=p=>p==='ETH'?((window.INKY&&INKY.weth)||'0x4200000000000000000000000000000000000006'):STOCK_ADDR[p];
  function drawPairs(){ g('pairMenu').innerHTML=PAIRS.map(x=>`<button type="button" class="${x[0]===pair?'on':''}" data-p="${x[0]}"><img src="${x[2]}" alt=""><span>${x[0]}<small>${x[1]}${PAIR_USD[x[0]]?' · $'+PAIR_USD[x[0]].toLocaleString('en-US',{maximumFractionDigits:2}):''}</small></span></button>`).join(''); }
  if(LIVE&&window.CHAIN) Promise.all(PAIRS.map(async p=>{ try{ PAIR_USD[p[0]]=await CHAIN.pairUsd(pairAddr(p[0])); }catch{} })).then(()=>{ drawPairs(); sync(); });
  g('pairMenu').addEventListener('click',e=>{ const b=e.target.closest('[data-p]'); if(!b) return; pair=b.dataset.p; g('pairMenu').classList.remove('open'); g('pairBtn').classList.remove('open'); drawPairs(); sync(); val2(); }); drawPairs();
  const COLORS=['var(--color-accent)','var(--color-success)','#fb923c','#60a5fa'];
  const letter=()=>((g('fTick').value.trim()||'T')[0]).toUpperCase();
  function paint(){ const l=letter(); g('pLetter').textContent=l; const av4=g('pLogo4').querySelector('span'); av4.textContent=l; [g('pLogo2'),g('pLogo4')].forEach(el=>{ el.querySelectorAll('img').forEach(i=>i.remove()); el.insertAdjacentHTML('beforeend',`<img src="${logoURL||DEF_LOGO}" alt="">`); }); const lb=g('pLogo'); if(logoURL) lb.innerHTML=`<img src="${logoURL}" alt="">`; }
  function val1(){ const n=g('fName').value.trim(), t=g('fTick').value.trim().toUpperCase(); let ok=true; g('nMsg').textContent=n?(n.length>32?'Name: 32 characters max':''):'Name is required'; if(!n||n.length>32) ok=false;
    if(!t){ g('tMsg').textContent=''; ok=false; } else if(!/^[A-Z0-9]{2,10}$/.test(t)){ g('tMsg').className='lf-err'; g('tMsg').textContent='Symbol: 2–10 characters, A–Z and 0–9'; ok=false; } else if(TAKEN.has(t)){ g('tMsg').className='lf-err'; g('tMsg').textContent='$'+t+' is already taken'; ok=false; } else { g('tMsg').className='lf-err ok'; g('tMsg').textContent='$'+t+' is available'; } return ok; }
  function val2(){ const c=parseFloat(g('fCommit').value)||0; const ok=!dev||(c>=0&&c<=0.5); g('cMsg').textContent=ok?'':'Dev buy must be between 0 and 0.5 ETH'; const need=rew&&pair==='ETH'&&!basket.length; g('pkMsg').textContent=need?'Pick at least one stock, or pair the token with a stock':''; return ok&&!need; }
  function donut(){ const n=basket.length, svg=g('donut'); const R=50, C=2*Math.PI*R; let off=0; svg.innerHTML=`<circle cx="60" cy="60" r="${R}" fill="none" stroke="var(--color-bg-input)" stroke-width="14"/>`+basket.map((s,i)=>{ const len=C/n-3; const el=`<circle cx="60" cy="60" r="${R}" fill="none" stroke="${COLORS[i]}" stroke-width="14" stroke-dasharray="${len} ${C-len}" stroke-dashoffset="${-off}" transform="rotate(-90 60 60)"/>`; off+=C/n; return el; }).join('');
    g('allocPct').textContent=n?Math.round(100/n)+'%':'0%'; g('allocLeft').textContent=n?`${n} of 4 picked · equal shares`:(pair==='ETH'?'Pick at least one stock':`No basket · paid in ${pair}`); g('allocLeft').style.color=n||pair!=='ETH'?'':'var(--color-error)';
    g('allocLegend').innerHTML=basket.map((s,i)=>`<div><span class="dot" style="background:${COLORS[i]}"></span>${STOCK_NAME[s]} · ${s}<b>${Math.round(100/n)}%</b></div>`).join(''); }
  function sync(){ const n=g('fName').value.trim()||'Your token', t=(g('fTick').value.trim()||'TOKEN').toUpperCase(), d=g('fDesc').value.trim(), c=parseFloat(g('fCommit').value)||0;
    g('pName').textContent=n; g('dName').textContent=n; g('pTick').textContent=t; g('pDesc').textContent=d||'Fixed-supply token trading on a locked Uniswap V4 pool.'; paint();
    const cUsd=c*ETH, out=cUsd/(CAP_USD+cUsd)*SUPPLY; g('fbOut').textContent=fmtAmt(out); g('dBuy').textContent=dev&&c?fmtAmt(out)+' tokens':'none'; g('sumDev').textContent=c+' ETH'; g('sumDevRow').style.display=dev?'':'none';
    const px=PAIR_USD[pair]||0, capPair=px?CAP_USD/px:0, unit=px?CAP_USD/SUPPLY/px:0; g('pairCur').innerHTML=`<img src="${pairImg2()}" alt="" class="lf-coin">${pair}`; g('pPair').textContent=pair; g('pPairTag').innerHTML=`<img src="${pairImg2()}" alt="">${pair}`; g('sumPair').textContent=pair; g('mktPool').textContent=`Uniswap V4 · ${pair} · Ink`; g('dPool').textContent=`Uniswap V4 · ${pair} · locked`;
    g('pvPrice').textContent=px?`${fmtPrice(unit)} ${pair} at the current ${pair} price.`:'Loading the '+pair+' price…'; g('pvCap').textContent=px?`${capPair>=100?capPair.toFixed(0):capPair.toFixed(2)} ${pair} at the current ${pair} price.`:'';
    const cr=rew?'0.70%':'1.20%', hd=rew?'0.50%':'0%'; g('spCreator').textContent=cr; g('spHolder').textContent=hd; g('spHoldL').textContent=rew?(basket.length?'Holders · in the basket':`Holders · in ${pair}`):'Holders · off'; g('mktFee').textContent=`2.00% · ${rew?'0.7 creator · 0.5 holders':'1.2 creator · 0 holders'} · 0.8 platform`;
    const rewTxt=rew?`0.5% · ${basket.join(', ')||pair}`:'Off · 1.2% to creator'; g('sumRew').textContent=rewTxt; g('dBasket').textContent=rewTxt; g('sumCreator').textContent=`${rew?'0.7':'1.2'}% of every trade`; g('dCreator').textContent=`${rew?'0.7':'1.2'}% of every trade`;
    g('pBasket').innerHTML=rew?(basket.map(s=>`<img src="${STOCK_IMG(s)}" alt="" title="${STOCK_NAME[s]}">`).join('')+(basket.join(', ')||`Rewards in ${pair}`)):'No holder rewards'; donut(); }
  function drawPick(){ g('pick').innerHTML=STOCKS.filter(s=>!LIVE||STOCK_ADDR[s[0]]).map(s=>{ const on=basket.includes(s[0]); const off=!on&&basket.length>=4; return `<button type="button" class="lf-pk${on?' on':''}${off?' off':''}" data-s="${s[0]}"><img src="${STOCK_IMG(s[0])}" alt=""><span class="t"><b>${s[0]}</b><span>${s[1]}${PAIR_USD[s[0]]?' · $'+PAIR_USD[s[0]].toLocaleString('en-US',{maximumFractionDigits:2}):''}</span></span><span class="lf-sw${on?' on':''}"></span></button>`; }).join(''); }
  g('pick').addEventListener('click',e=>{ const b=e.target.closest('[data-s]'); if(!b||b.classList.contains('off')) return; const s=b.dataset.s; basket=basket.includes(s)?basket.filter(x=>x!==s):[...basket,s]; drawPick(); sync(); val2(); }); drawPick();
  ['fName','fTick','fDesc','fCommit','fWeb','fX','fTg'].forEach(i=>g(i).addEventListener('input',()=>{ sync(); if(i==='fName'||i==='fTick') val1(); if(i==='fCommit') val2(); }));
  g('pairBtn').onclick=()=>{ g('pairBtn').classList.toggle('open'); g('pairMenu').classList.toggle('open'); }; g('mktBtn').onclick=()=>{ g('mktBtn').classList.toggle('open'); g('mkt').classList.toggle('open'); };
  const sw=(id,fn)=>{ const b=g(id); if(!b) return; b.onclick=()=>{ if(b.disabled) return; const on=!b.classList.contains('on'); b.classList.toggle('on',on); b.setAttribute('aria-checked',String(on)); fn&&fn(on); }; };
  sw('swDev',on=>{ dev=on; g('devBox').classList.toggle('open',on); sync(); val2(); }); sw('swRew',on=>{ rew=on; g('launchPage').classList.toggle('rew-off',!on); sync(); val2(); });
  function loadLogo(file){ if(!file||!file.type.startsWith('image/')){ toast('Please choose an image file','x'); return; } if(file.size>4*1024*1024){ toast('Logo too big, max 4 MB','x'); return; }
    const img=new Image(); img.onload=()=>{ const c=document.createElement('canvas'); c.width=c.height=192; const x=c.getContext('2d'); const s=Math.min(img.width,img.height); x.drawImage(img,(img.width-s)/2,(img.height-s)/2,s,s,0,0,192,192); let q=0.82; logoURL=c.toDataURL('image/webp',q); while(logoURL.length>24000&&q>0.3){ q-=0.12; logoURL=c.toDataURL('image/webp',q); } sync(); }; img.src=URL.createObjectURL(file); }
  g('fLogo').addEventListener('change',e=>loadLogo(e.target.files[0])); const dz=g('drop'); ['dragenter','dragover'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault(); dz.style.borderColor='var(--color-accent)';})); ['dragleave','drop'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault(); dz.style.borderColor='';})); dz.addEventListener('drop',e=>loadLogo(e.dataTransfer.files[0]));
  const cta=g('deploy'); const setCta=()=>{ if(busy) return; cta.disabled=false; cta.textContent=!W.connected?'Connect Wallet':!W.onInk?'Switch to Ink':'Launch token'; }; setCta(); document.addEventListener('wallet-change',setCta);
  const link=v=>{ v=v.trim(); if(!v) return ''; if(!/^https?:\/\//i.test(v)) v='https://'+v; return v.slice(0,200); };
  cta.onclick=async()=>{ if(!W.connected){ openConnect(); return; } if(!W.onInk){ try{ await DYN().switchToInk(); }catch(e){ toast(errMsg(e),'x'); } return; } if(!val1()||!val2()){ toast('Fix the highlighted fields','x'); $('main').scrollTo({top:0,behavior:'smooth'}); return; } if(PRE||!LIVE||!window.CHAIN){ toast('Launches open when the contracts go live on Ink'); return; }
    const name=g('fName').value.trim(), sym=g('fTick').value.trim().toUpperCase(); const meta={description:g('fDesc').value.trim().slice(0,280)}; if(logoURL) meta.image=logoURL; if(link(g('fWeb').value)) meta.website=link(g('fWeb').value); if(link(g('fX').value)) meta.x=link(g('fX').value); if(link(g('fTg').value)) meta.telegram=link(g('fTg').value);
    const devWei=dev?CHAIN.parseEther((parseFloat(g('fCommit').value)||0).toFixed(18)):0n; const bk=rew?basket.map(s=>STOCK_ADDR[s]).filter(Boolean):[];
    busy=true; cta.disabled=true; cta.textContent='Confirm in wallet…';
    try{ const {rc,token}=await CHAIN.launch({name,symbol:sym,metadataURI:JSON.stringify(meta),pair:pairAddr(pair),minPairOut:0,basket:bk,holderRewards:rew},devWei);
      busy=false; setCta(); if(!token) throw new Error('Launched, but the token address was not found in the receipt');
      g('dBlock').innerHTML=ic('check')+'Deployed · block #'+rc.blockNumber.toLocaleString(); g('dAddr').dataset.copy=cs(token); g('dAddrT').textContent=shortAddr(token); g('dOpen').href=tokenUrl(token.toLowerCase()); window._launched=token;
      $('.lf-grid').classList.add('hidden'); g('doneBox').classList.remove('hidden'); toast(name+' is live on Ink'); $('main').scrollTo({top:0,behavior:'smooth'}); try{ await CHAIN.refresh(); syncTok(); }catch{} }
    catch(e){ busy=false; setCta(); toast(errMsg(e),'x'); } };
  g('shareX').onclick=()=>{ const t=g('fTick').value.trim().toUpperCase(); const url=window._launched?SITE+'/token/'+window._launched.toLowerCase():SITE; open('https://x.com/intent/tweet?text='+encodeURIComponent('$'+t+' is live on Inkypump (Ink), paired with '+pair+'. LP locked forever.'+(rew?' Holders earn '+(basket.join(' + ')||pair)+' on every trade.':'')+' '+url)); };
  sync();
}

/* ======================= LEADERBOARD ======================= */
let BOARD=null;
async function initBoard(){
  const cards=$$('#boardPage .grid > div'); const setCard=(i,v,l)=>{ const d=cards[i].querySelector('.text-lg'); if(d) d.textContent=v; if(l){ const s=cards[i].querySelector('.text-xs span'); if(s) s.textContent=l; } };
  if(LIVE&&window.CHAIN){ try{ BOARD=await CHAIN.board(); }catch(e){ console.warn('board',e); } }
  const pool=BOARD?BOARD.pool:0; const payout=i=>i<5?pool/2*LB_TIER[i]/100:0;
  if(BOARD){ setCard(0,fmtEth(pool)); setCard(2,String(BOARD.traders)); setCard(3,BOARD.current>0?(BOARD.lastPaid>0?fmtEth(BOARD.lastPaid):'rolled over'):'—'); const ep=$('#boardPage h1 span'); if(ep) ep.textContent='Epoch '+(BOARD.epoch+1)+' · 3 days'; }
  function draw(kind){ const rows=BOARD?(kind==='pnl'?BOARD.pnl:BOARD.vol):[]; setTab('#btabs [data-board]',$(`#btabs [data-board="${kind}"]`));
    $('#podium').innerHTML=''; $('#bth').innerHTML=''; $('#btb').innerHTML=''; $('#bmob').innerHTML='';
    if(!rows.length){ const unq=BOARD&&BOARD.rows.length; $('#podium').insertAdjacentHTML('beforeend','<div class="o-feed-empty col-span-full">'+emptyBox(unq?'Nobody qualifies yet':'No trades yet',unq?'Wallets need $100 of volume this epoch to rank. '+BOARD.rows.length+' wallet'+(BOARD.rows.length>1?'s have':' has')+' traded so far.':'The first trade on any coin opens the board. Every trade counts, wherever it is sent from.',null,null,true)+'</div>'); return; }
    const me=W.connected&&W.address?W.address.toLowerCase():null; const val=r=>kind==='pnl'?r.pnl:r.fees; const vtxt=r=>kind==='pnl'?((r.pnl>=0?'+':'-')+fmtUsd(Math.abs(r.pnl))):fmtUsd(r.fees); const best=r=>{ const x=window.CHAIN&&CHAIN.token(r.best); return x?'<span class="inline-flex items-center justify-end gap-2">'+tokAv(x,'size-6 text-[10px]')+'<span class="font-medium">$'+esc(x.t)+'</span></span>':'—'; };
    $('#podium').innerHTML=rows.slice(0,3).map((r,i)=>`<div class="flex items-center gap-3 rounded-2xl px-4 py-3 ${r.wallet===me?'border border-accent/20 bg-accent/10':'bg-bg-input'}">${rank(i)}<div class="min-w-0 flex-1"><div class="flex items-center gap-2"><span class="truncate font-mono text-sm font-semibold text-text-primary">${shortAddr(r.wallet)}</span>${r.wallet===me?'<span class="inline-flex h-5 items-center rounded-full bg-accent px-2 text-[11px] font-semibold text-accent-ink">YOU</span>':''}</div><div class="mt-1 text-xs text-text-muted">${kind==='pnl'?'realized PnL':'fees paid · volume '+fmtUsd(r.volume)}</div></div><div class="shrink-0 text-right"><div class="text-[15px] font-semibold tabular-nums ${kind==='pnl'?(r.pnl>=0?'text-success':'text-error'):'text-text-primary'}">${vtxt(r)}</div><div class="mt-0.5 text-xs tabular-nums text-text-muted">payout ${fmtEth(payout(i))}</div></div></div>`).join('');
    const th=(t,w,a)=>`<th class="h-12 whitespace-nowrap bg-bg-input px-3 align-middle font-normal first:rounded-l-2xl first:pl-4 last:rounded-r-2xl last:pr-5 w-[${w}] text-${a}">${t}</th>`;
    $('#bth').innerHTML=th('#','7%','left')+th('Wallet','15%','left')+th(kind==='pnl'?'Realized PnL':'Fees paid','14%','right')+th('Volume','14%','right')+th('Trades','10%','right')+th('Best token','15%','right')+th('Payout','13%','right');
    const sixth=rows[5]?Math.max(0,val(rows[4])-val(rows[5])):0;
    $('#btb').innerHTML=rows.slice(0,25).map((r,i)=>`<tr class="h-[4.5rem] text-text-primary${r.wallet===me?' bg-accent/10':''}${i>=5?' opacity-60':''}">${tdiv('whitespace-nowrap px-4 py-3 align-middle',rank(i,true))}${tdiv('px-4 py-3 align-middle',wlink(shortAddr(r.wallet),r.wallet)+(r.wallet===me?tagS('YOU'):''))}${tdiv('px-4 py-3 align-middle text-right tabular-nums','<span class="block font-medium '+(kind==='pnl'?(r.pnl>=0?'text-success':'text-error'):'text-text-primary')+'">'+vtxt(r)+'</span>')}${tdiv('px-4 py-3 align-middle text-right tabular-nums',cellR(fmtUsd(r.volume)))}${tdiv('px-4 py-3 align-middle text-right tabular-nums',cellR(String(r.trades)))}${tdiv('px-4 py-3 align-middle text-right',best(r))}${tdiv('px-4 py-3 align-middle text-right tabular-nums',i<5?cellR(fmtEth(payout(i))):'<span class="block text-text-muted">—</span>')}</tr>`).join('')+(rows.length>5?`<tr><td colspan="7" class="px-4 py-4 text-center text-xs text-text-muted">only the top 5 are paid · #6 needs +${fmtUsd(sixth)} to get in</td></tr>`:'');
    $('#bmob').innerHTML=rows.slice(0,25).map((r,i)=>`<div class="flex items-center gap-3 border-b border-border-default py-3 last:border-b-0${i>=5?' opacity-60':''}">${rank(i,true)}<div class="min-w-0 flex-1"><div class="truncate font-mono text-sm font-semibold text-text-primary">${shortAddr(r.wallet)}${r.wallet===me?' <span class="text-accent">· you</span>':''}</div><div class="mt-0.5 text-xs text-text-muted">${r.trades} trades · volume ${fmtUsd(r.volume)}</div></div><div class="shrink-0 text-right"><div class="text-sm font-semibold tabular-nums ${kind==='pnl'?(r.pnl>=0?'text-success':'text-error'):'text-text-primary'}">${vtxt(r)}</div><div class="mt-0.5 text-xs text-text-muted">${i<5?'payout '+fmtEth(payout(i)):'—'}</div></div></div>`).join(''); }
  let kind='pnl'; $$('#btabs [data-board]').forEach(b=>b.onclick=()=>{ kind=b.dataset.board; draw(kind); }); draw(kind);
  const cd=$('#cd'); if(BOARD){ const paintCd=()=>{ const left=Math.max(0,BOARD.ends-Math.floor(Date.now()/1000)); cd.textContent=left?Math.floor(left/86400)+'d '+Math.floor(left%86400/3600)+'h '+Math.floor(left%3600/60)+'m':'settling'; }; paintCd(); setInterval(paintCd,30000); } else cd.textContent=PRE?'At launch':'—';
  boardYou();
  if(LIVE&&window.CHAIN) setInterval(async()=>{ if(document.hidden) return; try{ BOARD=await CHAIN.board(); draw(kind); boardYou(); setCard(0,fmtEth(BOARD.pool)); setCard(2,String(BOARD.traders)); }catch{} },20000);
}
let YOU_HTML=null;
function boardYou(){ const y=$('#youCard'); if(!y) return; if(YOU_HTML===null) YOU_HTML=y.innerHTML; else { y.innerHTML=YOU_HTML; y.style.cursor=''; y.onclick=null; }
  if(!W.connected){ y.innerHTML='<div class="flex h-7 items-center"><div class="text-lg font-semibold text-text-primary">Connect to see your rank</div></div><div class="mt-0.5 text-xs font-medium text-accent">Every trade counts, wherever you trade</div>'; y.style.cursor='pointer'; y.onclick=openConnect; return; }
  const me=W.address.toLowerCase(); const r=BOARD&&BOARD.rows.find(x=>x.wallet===me); if(!r){ y.innerHTML='<div class="flex h-7 items-center"><div class="text-lg font-semibold text-text-primary">No trades yet</div></div><div class="mt-0.5 text-xs font-medium text-accent">Your rank appears after your first trade</div>'; return; }
  const ip=BOARD.pnl.findIndex(x=>x.wallet===me), iv=BOARD.vol.findIndex(x=>x.wallet===me); const est=(ip>=0&&ip<5?BOARD.pool/2*LB_TIER[ip]/100:0)+(iv>=0&&iv<5?BOARD.pool/2*LB_TIER[iv]/100:0);
  y.innerHTML=`<div class="flex h-7 items-center"><div class="text-lg font-semibold tabular-nums text-text-primary">${ip>=0?'#'+(ip+1)+' PnL':r.volume<100?'Unranked':'—'}${iv>=0?' · #'+(iv+1)+' volume':''}</div></div><div class="mt-0.5 text-xs font-medium text-accent">${r.volume<100?'$'+(100-r.volume).toFixed(0)+' more volume to qualify':est>0?'est. payout '+fmtEth(est):(r.pnl>=0?'+':'-')+fmtUsd(Math.abs(r.pnl))+' realized · '+r.trades+' trades'}</div>`; }

/* ======================= PROFILE ======================= */
let PROFILE_HTML=null, profileSeq=0;
async function initProfile(){
  { const pg=$('#profilePage'); if(PROFILE_HTML===null) PROFILE_HTML=pg.innerHTML; else pg.innerHTML=PROFILE_HTML; }
  const seq=++profileSeq; const g=id=>document.getElementById(id);
  if(!W.connected){ const pg=$('#profilePage'); pg.innerHTML=`<div class="o-empty"><div class="ic">${ic('wallet')}</div><h2>Connect your wallet</h2><p>See your holdings, stock rewards, creator fees and leaderboard payouts in one place.</p><button id="pc">Connect Wallet</button></div>`; $('#pc').onclick=openConnect; return; }
  const a=W.address, me=a.toLowerCase();
  { const av=g('pfAv'); const wrap=av.parentElement; wrap.style.background=''; wrap.innerHTML=window.walletAvatar?walletAvatar(a,64).replace('width="64" height="64"','width="100%" height="100%"'):'<span class="absolute inset-0 flex items-center justify-center rounded-md font-bold text-white">'+a.slice(2,4).toUpperCase()+'</span>'; } g('pfAddrT').textContent=W.short; g('pfAddr').dataset.copy=a;
  const blocks=$$('#profilePage .items-stretch > div'); const setBlock=(i,v,s,cls)=>{ const vv=blocks[i].querySelector('.text-\\[26px\\]'), ss=blocks[i].querySelector('.font-mono'); vv.textContent=v; vv.className=vv.className.replace(/ text-(success|error|text-primary)/g,'')+' '+(cls||'text-text-primary'); if(ss){ ss.textContent=s; ss.className=ss.className.replace(/ text-(success|error|text-muted)/g,'')+' text-text-muted'; } };
  const tagHtml=(t,on)=>`<span class="inline-flex h-6 items-center gap-1.5 rounded-full px-2.5 text-xs font-semibold leading-none md:text-[11px] ${on?'bg-accent/10 text-accent':'bg-bg-input text-text-secondary'}">${t}</span>`;
  g('pfTags').innerHTML=tagHtml('Ink'); [0,1,2,3,4].forEach(i=>setBlock(i,['$0.00','$0.00','0 ETH','—','$0.00'][i],['No trades yet','across 0 coins','','not ranked','0 trades'][i]));
  const em=t=>'<div class="o-feed-empty">'+emptyBox(t,'Rewards, holdings and payouts show up here once you trade.',null,null,true)+'</div>';
  $('#rewards').innerHTML=em(LIVE?'Loading…':'Nothing to claim yet'); $('#htb').innerHTML=''; $('#hmob').innerHTML=em('No holdings yet'); $('#ctb').innerHTML=''; $('#cmob').innerHTML=em('No tokens created yet'); $('#act').innerHTML=em('No activity yet');
  $$('#ptabs [data-ptab]').forEach(b=>b.onclick=()=>{ setTab('#ptabs [data-ptab]',b); $$('#ppanes [data-ppane]').forEach(x=>x.classList.toggle('hidden',x.dataset.ppane!==b.dataset.ptab)); });
  g('claimAll').style.display='none';
  if(!LIVE||!window.CHAIN){ $('#rewards').innerHTML=em('Nothing to claim yet'); return; }
  let P, B; try{ [P,B]=await Promise.all([CHAIN.profile(me),CHAIN.board().catch(()=>null)]); }catch(e){ if(seq===profileSeq) toast('Could not load your profile: '+errMsg(e),'x'); return; } if(seq!==profileSeq) return;
  // header tags + stats
  const tags=[tagHtml('Ink')]; if(B){ const ip=B.pnl.findIndex(x=>x.wallet===me), iv=B.vol.findIndex(x=>x.wallet===me); if(ip>=0) tags.push(tagHtml(ic('trophy','size-3')+'#'+(ip+1)+' PnL this epoch',true)); if(iv>=0) tags.push(tagHtml(ic('trophy','size-3')+'#'+(iv+1)+' volume this epoch',true)); }
  P.created.forEach(c=>tags.push(tagHtml('Creator of '+esc(c.x.n)))); if(isAdmin()) tags.push(tagHtml('Operator',true)); g('pfTags').innerHTML=tags.join('');
  const total=P.holdings.reduce((s,h)=>s+h.bal*h.x.px,0); const pendUsd=P.holdings.reduce((s,h)=>s+h.pendUsd,0); const creFees=P.created.reduce((s,c)=>s+c.fees*c.x.pairUsd,0); const creEth=P.created.filter(c=>c.x.pair==='ETH').reduce((s,c)=>s+c.fees,0);
  setBlock(0,fmtUsd(total),(P.lifetimePnl>=0?'+':'-')+fmtUsd(Math.abs(P.lifetimePnl))+' realized lifetime'); setBlock(1,fmtUsd(pendUsd),'across '+P.holdings.filter(h=>h.pend>0).length+' coins',pendUsd>0?'text-success':'text-text-primary');
  setBlock(2,P.created.every(c=>c.x.pair==='ETH')?fmtEth(creEth):fmtUsd(creFees),P.created.length?fmtUsd(creFees)+' · '+P.created.map(c=>c.x.n).join(', '):'no tokens created');
  { const ip=B?B.pnl.findIndex(x=>x.wallet===me):-1, iv=B?B.vol.findIndex(x=>x.wallet===me):-1; const est=B?((ip>=0&&ip<5?B.pool/2*LB_TIER[ip]/100:0)+(iv>=0&&iv<5?B.pool/2*LB_TIER[iv]/100:0)):0; setBlock(3,ip>=0?'#'+(ip+1)+' PnL':iv>=0?'#'+(iv+1)+' volume':'—',(iv>=0&&ip>=0?'#'+(iv+1)+' volume · ':'')+(est>0?'est. '+fmtEth(est):P.payoutClaimable>0?fmtEth(P.payoutClaimable)+' claimable':'not ranked')); }
  setBlock(4,(P.epoch.pnl>=0?'+':'-')+fmtUsd(Math.abs(P.epoch.pnl)),P.epoch.trades+' trades · '+fmtUsd(P.epoch.volume)+' volume',P.epoch.trades?(P.epoch.pnl>=0?'text-success':'text-error'):'text-text-primary');
  // rewards list
  const rrow=(av,title,sub,val,btns)=>`<div class="flex min-w-0 items-center gap-3 border-b border-border-default px-4 py-3 last:border-b-0 hover:bg-bg-elevated">${av}<div class="min-w-0 flex-1"><div class="truncate text-sm font-semibold text-text-primary">${title}</div><div class="mt-1 truncate text-xs text-text-muted">${sub}</div></div><div class="hidden shrink-0 text-right sm:block"><div class="text-sm font-semibold tabular-nums text-success">${val}</div></div><div class="flex shrink-0 gap-1.5">${btns}</div></div>`;
  const items=[];
  P.holdings.filter(h=>h.pend>0&&h.x.rewards).forEach(h=>{ const x=h.x; const modes=x.basket.length?[['basket','Claim basket'],['eth','as ETH']]:x.pair==='ETH'?[['pair','Claim ETH']]:[['pair','Claim '+x.pair],['eth','as ETH']]; items.push(rrow(tokAv(x,'size-9 text-sm'),esc(x.n)+' · '+fmtUsd(h.pendUsd)+' pending','paid in '+rewardsOf(x).join(' · ')+' · '+inPair(h.pend,x),fmtUsd(h.pendUsd),modes.map((m,i)=>pb(m[1],'claim:'+x.addr+':'+m[0],i===0)).join(''))); });
  P.created.filter(c=>c.fees>0).forEach(c=>items.push(rrow(`<span class="flex size-9 shrink-0 items-center justify-center rounded-md bg-bg-elevated text-text-primary">${ic('coins')}</span>`,'Creator fees · '+esc(c.x.n),(c.x.creatorBps*2/10000).toFixed(1)+'% of every trade · lifetime '+inPair(c.x.totalCreatorFees,c.x),inPair(c.fees,c.x),pb('Claim','pay:'+c.x.addr,1))));
  if(P.payoutClaimable>0) items.push(rrow(`<span class="flex size-9 shrink-0 items-center justify-center rounded-md bg-bg-elevated text-text-primary">${ic('trophy')}</span>`,'Leaderboard payout','settled epochs · paid in ETH',fmtEth(P.payoutClaimable),pb('Claim','payout',1)));
  $('#rewards').innerHTML=items.join('')||em('Nothing to claim yet');
  const act=async(b)=>{ const [k,addr,mode]=b.dataset.act.split(':'); const ok=await runTx(b,()=>k==='claim'?CHAIN.claim(addr,mode):k==='pay'?CHAIN.payCreator(addr):CHAIN.claimPayout(),k==='claim'?'Rewards claimed':k==='pay'?'Creator fees paid out':'Payout claimed'); if(ok) initProfile(); };
  $$('#rewards [data-act]').forEach(b=>b.onclick=()=>act(b));
  if(items.length){ g('claimAll').style.display=''; g('claimAll').onclick=async()=>{ const bs=$$('#rewards [data-act]').filter(b=>b.dataset.act.startsWith('claim:')&&(b.dataset.act.endsWith(':basket')||b.dataset.act.endsWith(':pair'))||!b.dataset.act.startsWith('claim:')); for(const b of bs){ const ok=await runTx(b,()=>{ const [k,addr,mode]=b.dataset.act.split(':'); return k==='claim'?CHAIN.claim(addr,mode):k==='pay'?CHAIN.payCreator(addr):CHAIN.claimPayout(); }); if(!ok) break; } toast('All rewards claimed'); initProfile(); }; }
  // holdings
  const H=P.holdings.filter(h=>h.bal>0);
  $('#htb').innerHTML=H.map(h=>{ const x=h.x, v=h.bal*x.px, p=h.avg>0?(x.pxPair/h.avg-1)*100:null; return `<tr class="h-[4.5rem] cursor-pointer text-text-primary hover:bg-bg-elevated" onclick="location.href='${tokenUrl(x)}'">${tdiv('px-4 py-3 align-middle','<span class="flex items-center gap-3">'+tokAv(x,'size-9 text-sm')+'<span class="min-w-0"><span class="block truncate text-sm font-bold">'+esc(x.t)+'</span><span class="block truncate text-xs text-text-muted">'+esc(x.n)+'</span></span></span>')}${tdiv('px-4 py-3 align-middle text-right tabular-nums',cellR(fmtAmt(h.bal)))}${tdiv('px-4 py-3 align-middle text-right tabular-nums',cellR(fmtUsd(v),inPair(h.bal*x.pxPair,x)))}${tdiv('px-4 py-3 align-middle text-right tabular-nums',cellR(h.avg>0?'$'+fmtPrice(h.avg*x.pairUsd):'—'))}${tdiv('px-4 py-3 align-middle text-right tabular-nums',p==null?'<span class="block text-text-muted">—</span>':'<span class="block font-medium '+(p>=0?'text-success':'text-error')+'">'+(p>=0?'+':'')+p.toFixed(1)+'%</span>')}${tdiv('px-4 py-3 align-middle text-right','<span class="inline-flex justify-end gap-1">'+(rewardsOf(x).map(s=>stockAv(s,'size-5 text-[9px]')).join('')||'<span class="text-xs text-text-muted">off</span>')+'</span>')}${tdiv('px-4 py-3 align-middle text-right tabular-nums','<span class="block font-medium '+(h.pend>0?'text-success':'text-text-muted')+'">'+fmtUsd(h.pendUsd)+'</span>')}${tdiv('px-4 py-3 align-middle text-right','<span class="inline-flex gap-1" onclick="event.stopPropagation()"><a class="inline-flex h-8 items-center rounded-full bg-bg-elevated px-3 text-xs font-semibold text-text-primary hover:bg-bg-selector-hover" href="'+tokenUrl(x)+'?side=sell">Sell</a></span>')}</tr>`; }).join('');
  $('#hmob').innerHTML=H.map(h=>{ const x=h.x, v=h.bal*x.px, p=h.avg>0?(x.pxPair/h.avg-1)*100:null; return `<a class="flex items-center gap-3 border-b border-border-default py-3.5 last:border-b-0" href="${tokenUrl(x)}">${tokAv(x,'size-11 text-sm')}<div class="min-w-0 flex-1"><div class="flex min-w-0 items-center gap-2"><span class="truncate text-sm font-bold text-text-primary">${esc(x.t)}</span><span class="truncate text-sm font-medium text-text-muted">${esc(x.n)}</span></div><div class="mt-1 flex items-center gap-1.5 text-[13px] leading-none text-text-muted"><span>${fmtAmt(h.bal)}</span><span class="text-text-disabled">·</span><span class="${h.pend>0?'text-success':''}">${fmtUsd(h.pendUsd)} pending</span></div></div><div class="shrink-0 text-right"><div class="text-[15px] font-medium tabular-nums text-text-primary">${fmtUsd(v)}</div><div class="mt-0.5 text-xs tabular-nums ${p==null?'text-text-muted':p>=0?'text-success':'text-error'}">${p==null?'—':(p>=0?'+':'')+p.toFixed(1)+'%'}</div></div></a>`; }).join('')||em('No holdings yet');
  // created
  $('#ctb').innerHTML=P.created.map(c=>{ const x=c.x; return `<tr class="h-[4.5rem] cursor-pointer text-text-primary hover:bg-bg-elevated" onclick="location.href='${tokenUrl(x)}'">${tdiv('px-4 py-3 align-middle','<span class="flex items-center gap-3">'+tokAv(x,'size-9 text-sm')+'<span class="min-w-0"><span class="block truncate text-sm font-bold">'+esc(x.t)+'</span><span class="block truncate text-xs text-text-muted">'+esc(x.n)+'</span></span></span>')}${tdiv('px-4 py-3 align-middle text-right tabular-nums',cellR(fmtUsd(x.mc)))}${tdiv('px-4 py-3 align-middle text-right tabular-nums',cellR(fmtUsd(x.vol)))}${tdiv('px-4 py-3 align-middle text-right tabular-nums',cellR(x.h.toLocaleString()))}${tdiv('px-4 py-3 align-middle text-right tabular-nums',cellR(fmtUsd(x.totalCreatorFees*x.pairUsd),inPair(x.totalCreatorFees,x)+' lifetime'))}${tdiv('px-4 py-3 align-middle text-right tabular-nums','<span class="block font-medium '+(c.fees>0?'text-success':'text-text-muted')+'">'+inPair(c.fees,x)+'</span>')}${tdiv('px-4 py-3 align-middle text-right','<span class="inline-flex gap-1" onclick="event.stopPropagation()">'+pb('Claim','pay:'+x.addr,1,c.fees>0?'':'disabled')+'</span>')}</tr>`; }).join('');
  $('#cmob').innerHTML=P.created.map(c=>{ const x=c.x; return `<a class="flex items-center gap-3 py-3.5" href="${tokenUrl(x)}">${tokAv(x,'size-11 text-sm')}<div class="min-w-0 flex-1"><div class="text-sm font-bold text-text-primary">${esc(x.t)}</div><div class="mt-1 text-[13px] leading-none text-text-muted">${fmtUsd(x.mc)} mcap · ${x.h.toLocaleString()} holders</div></div><div class="shrink-0 text-right"><div class="text-[15px] font-medium ${c.fees>0?'text-success':'text-text-muted'}">${inPair(c.fees,x)}</div><div class="mt-0.5 text-xs text-text-muted">claimable</div></div></a>`; }).join('')||em('No tokens created yet');
  $$('#ctb [data-act]').forEach(b=>b.onclick=()=>act(b));
  // activity
  const ACT=[]; P.trades.forEach(t=>{ const x=CHAIN.token(t.token); if(!x) return; const coin=Number(t.coin)/1e18, pair=Number(t.pair)/1e18, rz=Number(t.realized)/1e18; ACT.push({ts:t.ts,k:t.buy?'Buy':'Sell',cls:t.buy?'text-success':'text-error',txt:t.buy?inPair(pair,x)+' → '+fmtAmt(coin)+' '+esc(x.t):fmtAmt(coin)+' '+esc(x.t)+' → '+inPair(pair,x)+(rz?' · '+(rz>=0?'+':'')+inPair(Math.abs(rz),x).replace(/^/,rz<0?'-':'')+' realized':''),tx:t.tx}); });
  P.claims.forEach(c=>{ const x=CHAIN.token(c.token); if(!x) return; ACT.push({ts:c.ts,k:c.payout===1?'Claim as ETH':'Claim',cls:'text-success',txt:inPair(c.amount,x)+' · '+esc(x.n)+' rewards'+(c.payout===2?' → '+x.basket.join(' + '):''),tx:c.tx}); });
  P.created.forEach(c=>ACT.push({ts:c.x.createdAt,k:'Launch',cls:'text-text-primary',txt:esc(c.x.n)+' · $'+esc(c.x.t)+' deployed · '+(c.x.rewards?'basket '+rewardsOf(c.x).join(' '):'no holder rewards'),tx:null}));
  ACT.sort((a,b)=>b.ts-a.ts);
  $('#act').innerHTML=ACT.map(a=>`<div class="flex items-center gap-3 border-b border-border-default py-3.5 last:border-b-0"><span class="w-[72px] shrink-0 text-xs text-text-muted">${ago(Math.max(0,Math.floor(Date.now()/1000)-a.ts))} ago</span><div class="min-w-0 flex-1 text-sm"><span class="font-semibold ${a.cls}">${a.k}</span> <span class="text-text-secondary">${a.txt}</span></div>${a.tx?`<a class="inline-flex text-text-muted hover:text-accent" href="${EXPLORER}/tx/${a.tx}" target="_blank" rel="noopener noreferrer">${ic('ext','size-3.5')}</a>`:''}</div>`).join('')||em('No activity yet');
}

/* ======================= DOCS ======================= */
function initDocs(){ const links=$$('#toc a'); const main=$('main'); const hs=links.map(a=>$(a.getAttribute('href'))); const io=new IntersectionObserver(es=>{ es.forEach(e=>{ if(e.isIntersecting) links.forEach(a=>a.classList.toggle('on',a.getAttribute('href')==='#'+e.target.id)); }); },{root:main,rootMargin:'-10% 0px -80% 0px'}); hs.forEach(h=>h&&io.observe(h));
  links.forEach(a=>a.onclick=e=>{ e.preventDefault(); const t=$(a.getAttribute('href')); if(t) main.scrollTo({top:t.offsetTop-24,behavior:'smooth'}); history.replaceState(null,'',a.getAttribute('href')); });
  if(location.hash){ const t=$(location.hash); if(t) setTimeout(()=>main.scrollTo({top:t.offsetTop-24}),50); } }

/* ======================= OPERATOR (unlisted /admin) ======================= */
async function initAdmin(){
  const b=$('#admBody'); if(!W.connected){ b.innerHTML=`<div class="o-empty"><div class="ic">${ic('shield')}</div><h2>Admin wallet only</h2><p>Connect the admin wallet to settle epochs, hide tokens and sweep the treasury.</p><button id="pc">Connect Wallet</button></div>`; $('#pc').onclick=openConnect; return; }
  if(!isAdmin()){ b.innerHTML=`<div class="o-empty"><div class="ic">${ic('shield')}</div><h2>Not the admin wallet</h2><p>${W.short} is not the admin of these contracts. Nothing here would go through.</p></div>`; return; }
  if(!LIVE||!window.CHAIN){ b.innerHTML=emptyBox('Contracts not live','Operator tools need the live contracts.',null,null,true); return; }
  b.innerHTML='<p class="text-sm text-text-muted">Loading…</p>';
  try{ await initAdminBody(b); }catch(e){ b.innerHTML=`<div class="o-empty sm"><div class="ic">${ic('x')}</div><h2>Could not load</h2><p>${esc(errMsg(e))}</p><button id="admRetry">Retry</button></div>`; $('#admRetry').onclick=()=>initAdmin(); }
}
async function initAdminBody(b){
  const cur=await CHAIN.currentEpoch(); const prev=cur-1; const [board,prevBoard,prevSettled,tw]=await Promise.all([CHAIN.board(),prev>=0?CHAIN.board(prev):null,prev>=0?CHAIN.settled(prev):true,CHAIN.treasuryWeth()]);
  const all=CHAIN.tokens(); const [owed,feeTo,trTo]=await Promise.all([Promise.all(all.map(x=>CHAIN.platformOwed(x.addr).catch(()=>0))),CHAIN.feeRecipient().catch(()=>''),CHAIN.treasuryRecipient()]);
  const wl=w=>`<code>${shortAddr(w)}</code>`; const list=(rows,k)=>rows.slice(0,5).map((r,i)=>`<div class="flex justify-between text-xs"><span>#${i+1} ${wl(r.wallet)}</span><b>${k==='pnl'?(r.pnl>=0?'+':'-')+fmtUsd(Math.abs(r.pnl)):fmtUsd(r.fees)}</b></div>`).join('')||'<div class="text-xs text-text-muted">nobody qualified</div>';
  b.innerHTML=`<div class="adm-grid">
    <div class="adm-card"><h4>Epoch ${cur+1} · live</h4><p>Pool ${fmtEth(board.pool)} · ${board.traders} traders · ends ${new Date(board.ends*1000).toLocaleString()}</p><p class="text-xs">PnL board</p>${list(board.pnl,'pnl')}<p class="text-xs">Volume board</p>${list(board.vol,'vol')}</div>
    <div class="adm-card"><h4>Epoch ${prev+1} · ${prev<0?'none yet':prevSettled?'settled':'ready to settle'}</h4>${prevBoard?`<p>Pays ${fmtEth(board.pool)} split in half per board, tiered 40/25/15/12/8.</p><p class="text-xs">PnL winners</p>${list(prevBoard.pnl,'pnl')}<p class="text-xs">Volume winners</p>${list(prevBoard.vol,'vol')}<div class="row"><button class="adm-btn" id="admSettle" ${prevSettled?'disabled':''}>${prevSettled?'Already settled':'Settle epoch '+(prev+1)}</button></div>`:'<p>The first epoch is still running.</p>'}</div>
    <div class="adm-card"><h4>Treasury</h4><p>${fmtEth(tw)} WETH waiting. Sweep sends an eighth of the platform share to the leaderboard pool and the rest to the fee recipient. Anyone can call it.</p><p>Unpushed platform fees across tokens: ${fmtEth(owed.reduce((s,v)=>s+v,0))}.</p><div class="row"><button class="adm-btn" id="admPush" ${owed.some(v=>v>0)?'':'disabled'}>Push platform fees</button><button class="adm-btn" id="admSweep" ${tw>0?'':'disabled'}>Sweep WETH</button></div></div>
    <div class="adm-card"><h4>Collect liquidity</h4><p>Pull part of a coin's launch position (coins and pair) out of the pool to a recipient. Emergency only; it is not reversible and it moves the price.</p><select class="adm-in" id="admColTok">${all.map(x=>`<option value="${x.addr}">${esc(x.t)} · ${esc(x.n)}</option>`).join('')}</select><input class="adm-in" id="admColBps" placeholder="share in bps · 10000 = all" inputmode="numeric"><input class="adm-in" id="admColTo" placeholder="recipient 0x…" value="${esc(W.address)}"><div class="row"><button class="adm-btn danger" id="admCollect" ${all.length?'':'disabled'}>Collect</button></div></div>
    <div class="adm-card"><h4>Recipients</h4><p>Platform fees go from the coins to the treasury, then an eighth to the payout pool and the rest to the treasury recipient.</p><p class="text-xs">Factory fee recipient <code>${esc(feeTo)}</code></p><input class="adm-in" id="admFeeTo" placeholder="new factory fee recipient 0x…"><div class="row"><button class="adm-btn" id="admFeeSet">Set fee recipient</button></div><p class="text-xs">Treasury recipient <code>${esc(trTo)}</code></p><input class="adm-in" id="admTrTo" placeholder="new treasury recipient 0x…"><div class="row"><button class="adm-btn" id="admTrSet">Set treasury recipient</button></div></div>
    <div class="adm-card"><h4>Quote assets</h4><p>Approve or disable a paired asset (18-decimal token). Price from a Chainlink feed (8 decimals) or a fixed USD price in 8 decimals.</p><input class="adm-in" id="admQaPair" placeholder="asset 0x…"><input class="adm-in" id="admQaFeed" placeholder="price feed 0x… (optional)"><input class="adm-in" id="admQaPx" placeholder="fixed usd price ×1e8 (if no feed)" inputmode="numeric"><div class="row"><button class="adm-btn" id="admQaOn">Approve</button><button class="adm-btn danger" id="admQaOff">Disable</button></div></div>
    <div class="adm-card" style="grid-column:1/-1"><h4>Tokens</h4><p>Hidden tokens stay tradable and keep paying fees; they just leave the feed, search and trending.</p>
      ${all.map((x,i)=>`<div class="flex items-center gap-3 border-b border-border-default py-2 last:border-b-0 text-sm"><span class="min-w-0 flex-1 truncate"><b>${esc(x.t)}</b> <span class="text-text-muted">${esc(x.n)}</span> <code>${x.addr}</code></span><span class="text-xs text-text-muted">${fmtUsd(x.mc)} · platform owed ${inPair(owed[i],x)}</span><button class="adm-btn sm" data-hide="${x.addr}" data-v="${x.hidden?'0':'1'}">${x.hidden?'Unhide':'Hide'}</button><button class="adm-btn sm" data-meta="${x.addr}">Metadata</button></div>`).join('')||'<p>No tokens yet.</p>'}</div>
  </div>`;
  const re=()=>initAdmin();
  const s=$('#admSettle'); if(s&&!prevSettled) s.onclick=()=>runTx(s,()=>CHAIN.settle(prev,prevBoard.pnl.slice(0,5).map(r=>r.wallet),prevBoard.vol.slice(0,5).map(r=>r.wallet)),'Epoch settled').then(ok=>ok&&re());
  const p=$('#admPush'); if(p) p.onclick=()=>runTx(p,()=>CHAIN.pushPlatformFees(all.filter((x,i)=>owed[i]>0).map(x=>x.addr)),'Platform fees pushed').then(ok=>ok&&re());
  const sw=$('#admSweep'); if(sw) sw.onclick=()=>runTx(sw,()=>CHAIN.sweep(),'Treasury swept').then(ok=>ok&&re());
  const addr=v=>{ v=(v||'').trim(); if(!CHAIN.isAddress(v)){ toast('Not a valid address','x'); return null; } return v; };
  const col=$('#admCollect'); if(col) col.onclick=()=>{ const t=$('#admColTok').value, bps=parseInt($('#admColBps').value)||0, to=addr($('#admColTo').value); if(!to) return; if(bps<1||bps>10000) return toast('Share must be 1 to 10000 bps','x'); const x=CHAIN.token(t); if(!confirm(`Collect ${(bps/100).toFixed(2)}% of the ${x.t} launch position to ${to}? This cannot be undone.`)) return; runTx(col,()=>CHAIN.collect(t,bps,to),'Liquidity collected').then(async ok=>{ if(ok){ await CHAIN.refresh(t); re(); } }); };
  const fs=$('#admFeeSet'); if(fs) fs.onclick=()=>{ const a=addr($('#admFeeTo').value); if(a) runTx(fs,()=>CHAIN.setFeeRecipient(a),'Fee recipient set').then(ok=>ok&&re()); };
  const ts=$('#admTrSet'); if(ts) ts.onclick=()=>{ const a=addr($('#admTrTo').value); if(a) runTx(ts,()=>CHAIN.setTreasuryRecipient(a),'Treasury recipient set').then(ok=>ok&&re()); };
  const qa=on=>{ const pair=addr($('#admQaPair').value); if(!pair) return; const feed=$('#admQaFeed').value.trim(); const px=parseInt($('#admQaPx').value)||0; if(feed&&!CHAIN.isAddress(feed)) return toast('Feed is not a valid address','x'); if(on&&!feed&&!px) return toast('Give a feed or a fixed price','x'); const b=on?$('#admQaOn'):$('#admQaOff'); runTx(b,()=>CHAIN.setQuoteAsset(pair,on,on?px:0,on?feed:''),on?'Quote asset approved':'Quote asset disabled'); };
  $('#admQaOn').onclick=()=>qa(true); $('#admQaOff').onclick=()=>qa(false);
  $$('[data-hide]').forEach(h=>h.onclick=()=>runTx(h,()=>CHAIN.setHidden(h.dataset.hide,h.dataset.v==='1'),h.dataset.v==='1'?'Token hidden':'Token visible again').then(async ok=>{ if(ok){ await CHAIN.refresh(h.dataset.hide); re(); } }));
  $$('[data-meta]').forEach(m=>m.onclick=()=>{ const x=CHAIN.token(m.dataset.meta); const ov=dialog(dh('Metadata override · '+esc(x.t),'JSON with description, image, website, x, telegram. Empty restores the original.')+`<div class="db"><textarea class="adm-in" id="admMetaIn" style="height:140px;padding:10px 12px;font-size:12px">${esc(JSON.stringify({description:x.desc,image:x.img?'(unchanged)':'',website:x.links.web,x:x.links.x,telegram:x.links.tg},null,1))}</textarea><div class="row" style="margin-top:10px"><button class="adm-btn" id="admMetaGo">Save on-chain</button></div></div>`);
    $('#admMetaGo',ov).onclick=()=>{ let v=$('#admMetaIn',ov).value.trim(); if(v){ try{ const j=JSON.parse(v); if(j.image==='(unchanged)') j.image=x.img; v=JSON.stringify(j); }catch{ return toast('Not valid JSON','x'); } } runTx($('#admMetaGo',ov),()=>CHAIN.setMetadata(x.addr,v),'Metadata saved').then(async ok=>{ if(ok){ ov.remove(); location.reload(); } }); }; });
}

document.addEventListener('data-ready',()=>{ if($('#launchPage')) initLaunch(); if($('#boardPage')) initBoard(); if($('#profilePage')) initProfile(); if($('#docsPage')) initDocs(); if($('#adminPage')) initAdmin(); });
document.addEventListener('wallet-change',()=>{ if($('#profilePage')) initProfile(); if($('#boardPage')) boardYou(); if($('#adminPage')) initAdmin(); });
