/* behaviour for launch / profile / leaderboard / docs / admin */
const stockAv=(s,sz)=>`<span class="relative flex shrink-0 overflow-hidden rounded-full bg-avatar-gradient ring-1 ring-inset ring-text-primary/10 ${sz}"><span class="absolute inset-0 flex items-center justify-center font-bold text-text-primary">${s[0]}</span><img alt="" class="absolute inset-0 size-full object-cover" src="${STOCK_IMG(s)}"></span>`;
const stockTag=s=>`<span class="inline-flex h-6 items-center gap-1.5 rounded-full px-2.5 text-xs font-semibold leading-none md:text-[11px] bg-bg-input text-text-secondary" title="${STOCK_NAME[s]}">${stockAv(s,'-ml-1 size-4.5')}${s}</span>`;
const tokAv=(x,sz,extra='')=>`<span class="relative flex shrink-0 overflow-hidden rounded-md bg-avatar-gradient ring-1 ring-inset ring-text-primary/10 ${sz} ${extra}"><span class="absolute inset-0 flex items-center justify-center rounded-md font-bold text-text-primary">${x.t[0]}</span><img alt="" class="absolute inset-0 size-full rounded-md object-cover" src="${x.img||DEF_LOGO}" onerror="this.onerror=null;this.src='${DEF_LOGO}'"></span>`;
const setTab=(sel,on,offCls='text-text-muted hover:text-text-secondary')=>$$(sel).forEach(b=>{ b.className=b.className.replace(/ text-text-primary| text-text-muted hover:text-text-secondary/g,'')+(b===on?' text-text-primary':' '+offCls); });

/* ======================= LAUNCH ======================= */
function initLaunch(){
  const g=id=>document.getElementById(id); const TAKEN=new Set(TOK.map(x=>x.t)); let basket=['NVDAx','SPYx'], logoURL=null, dev=false, pair='ETH', rew=true;
  const PAIR_USD={ETH:ETH,NVDAx:185.2,SPYx:650.4,QQQx:571.1,TSLAx:431.5,AAPLx:255.8,MSTRx:328.9,SPCXx:212.0,PLTRx:168.3,NFLXx:1185.0};
  const PAIRS=[['ETH','Ethereum',ETH_IMG],...STOCKS.map(x=>[x[0],x[1],STOCK_IMG(x[0])])]; const pairImg=()=>PAIRS.find(x=>x[0]===pair)[2]; const CAP_USD=3000;
  function drawPairs(){ g('pairMenu').innerHTML=PAIRS.map(x=>`<button type="button" class="${x[0]===pair?'on':''}" data-p="${x[0]}"><img src="${x[2]}" alt=""><span>${x[0]}<small>${x[1]} · $${PAIR_USD[x[0]].toLocaleString('en-US',{maximumFractionDigits:2})}</small></span></button>`).join(''); }
  g('pairMenu').addEventListener('click',e=>{ const b=e.target.closest('[data-p]'); if(!b) return; pair=b.dataset.p; g('pairMenu').classList.remove('open'); g('pairBtn').classList.remove('open'); drawPairs(); sync(); val2(); }); drawPairs();
  const COLORS=['var(--color-accent)','var(--color-success)','#fb923c','#60a5fa'];
  const letter=()=>((g('fTick').value.trim()||'T')[0]).toUpperCase();
  function paint(){ const l=letter(); g('pLetter').textContent=l; const av4=g('pLogo4').querySelector('span'); av4.textContent=l; [g('pLogo2'),g('pLogo4')].forEach(el=>{ el.querySelectorAll('img').forEach(i=>i.remove()); el.insertAdjacentHTML('beforeend',`<img src="${logoURL||DEF_LOGO}" alt="">`); }); const lb=g('pLogo'); if(logoURL) lb.innerHTML=`<img src="${logoURL}" alt="">`; }
  function val1(){ const n=g('fName').value.trim(), t=g('fTick').value.trim().toUpperCase(); let ok=true; g('nMsg').textContent=n?'':'Name is required'; if(!n) ok=false;
    if(!t){ g('tMsg').textContent=''; ok=false; } else if(!/^[A-Z0-9]{2,10}$/.test(t)){ g('tMsg').className='lf-err'; g('tMsg').textContent='Symbol: 2–10 characters, A–Z and 0–9'; ok=false; } else if(TAKEN.has(t)){ g('tMsg').className='lf-err'; g('tMsg').textContent='$'+t+' is already taken'; ok=false; } else { g('tMsg').className='lf-err ok'; g('tMsg').textContent='$'+t+' is available'; } return ok; }
  function val2(){ const c=parseFloat(g('fCommit').value)||0; const ok=!dev||(c>=0&&c<=0.5); g('cMsg').textContent=ok?'':'Dev buy must be between 0 and 0.5 ETH'; const need=rew&&pair==='ETH'&&!basket.length; g('pkMsg').textContent=need?'Pick at least one stock, or pair the token with a stock':''; return ok&&!need; }
  function donut(){ const n=basket.length, svg=g('donut'); const R=50, C=2*Math.PI*R; let off=0; svg.innerHTML=`<circle cx="60" cy="60" r="${R}" fill="none" stroke="var(--color-bg-input)" stroke-width="14"/>`+basket.map((s,i)=>{ const len=C/n-3; const el=`<circle cx="60" cy="60" r="${R}" fill="none" stroke="${COLORS[i]}" stroke-width="14" stroke-dasharray="${len} ${C-len}" stroke-dashoffset="${-off}" transform="rotate(-90 60 60)"/>`; off+=C/n; return el; }).join('');
    g('allocPct').textContent=n?Math.round(100/n)+'%':'0%'; g('allocLeft').textContent=n?`${n} of 4 picked · equal shares`:(pair==='ETH'?'Pick at least one stock':`No basket · paid in ${pair}`); g('allocLeft').style.color=n||pair!=='ETH'?'':'var(--color-error)';
    g('allocLegend').innerHTML=basket.map((s,i)=>`<div><span class="dot" style="background:${COLORS[i]}"></span>${STOCK_NAME[s]} · ${s}<b>${Math.round(100/n)}%</b></div>`).join(''); }
  function sync(){ const n=g('fName').value.trim()||'Your token', t=(g('fTick').value.trim()||'TOKEN').toUpperCase(), d=g('fDesc').value.trim(), c=parseFloat(g('fCommit').value)||0;
    g('pName').textContent=n; g('dName').textContent=n; g('pTick').textContent=t; g('pDesc').textContent=d||'Fixed-supply token trading on a locked Uniswap V4 pool.'; paint();
    const cUsd=c*ETH, out=cUsd/(CAP_USD+cUsd)*SUPPLY; g('fbOut').textContent=fmtAmt(out); g('dBuy').textContent=dev?fmtAmt(out)+' tokens':'none'; g('sumDev').textContent=c+' ETH'; g('sumDevRow').style.display=dev?'':'none';
    // pair + fee split
    const px=PAIR_USD[pair], capPair=CAP_USD/px, unit=CAP_USD/SUPPLY/px; g('pairCur').innerHTML=`<img src="${pairImg()}" alt="" class="lf-coin">${pair}`; g('pPair').textContent=pair; g('pPairTag').innerHTML=`<img src="${pairImg()}" alt="">${pair}`; g('sumPair').textContent=pair; g('mktPool').textContent=`Uniswap V4 · ${pair} · Ink`; g('dPool').textContent=`Uniswap V4 · ${pair} · locked`;
    g('pvPrice').textContent=`${fmtPrice(unit)} ${pair} at the current ${pair} price.`; g('pvCap').textContent=`${capPair>=100?capPair.toFixed(0):capPair.toFixed(2)} ${pair} at the current ${pair} price.`;
    const cr=rew?'0.70%':'1.20%', hd=rew?'0.50%':'0%'; g('spCreator').textContent=cr; g('spHolder').textContent=hd; g('spHoldL').textContent=rew?(basket.length?'Holders · in the basket':`Holders · in ${pair}`):'Holders · off'; g('mktFee').textContent=`2.00% · ${rew?'0.7 creator · 0.5 holders':'1.2 creator · 0 holders'} · 0.8 platform`;
    const rewTxt=rew?`0.5% · ${basket.join(', ')||pair}`:'Off · 1.2% to creator'; g('sumRew').textContent=rewTxt; g('dBasket').textContent=rewTxt; g('sumCreator').textContent=`${rew?'0.7':'1.2'}% of every trade`; g('dCreator').textContent=`${rew?'0.7':'1.2'}% of every trade`;
    g('pBasket').innerHTML=rew?(basket.map(s=>`<img src="${STOCK_IMG(s)}" alt="" title="${STOCK_NAME[s]}">`).join('')+(basket.join(', ')||`Rewards in ${pair}`)):'No holder rewards'; donut(); }
  function drawPick(){ g('pick').innerHTML=STOCKS.map(s=>{ const on=basket.includes(s[0]); const off=!on&&basket.length>=4; return `<button type="button" class="lf-pk${on?' on':''}${off?' off':''}" data-s="${s[0]}"><img src="${STOCK_IMG(s[0])}" alt=""><span class="t"><b>${s[0]}</b><span>${s[1]} · liq ${fmtUsd(s[3])}</span></span><span class="lf-sw${on?' on':''}"></span></button>`; }).join(''); }
  g('pick').addEventListener('click',e=>{ const b=e.target.closest('[data-s]'); if(!b||b.classList.contains('off')) return; const s=b.dataset.s; basket=basket.includes(s)?basket.filter(x=>x!==s):[...basket,s]; drawPick(); sync(); val2(); }); drawPick();
  ['fName','fTick','fDesc','fCommit','fWeb','fX','fTg'].forEach(i=>g(i).addEventListener('input',()=>{ sync(); if(i==='fName'||i==='fTick') val1(); if(i==='fCommit') val2(); }));
  g('pairBtn').onclick=()=>{ g('pairBtn').classList.toggle('open'); g('pairMenu').classList.toggle('open'); }; g('mktBtn').onclick=()=>{ g('mktBtn').classList.toggle('open'); g('mkt').classList.toggle('open'); };
  const sw=(id,fn)=>{ const b=g(id); b.onclick=()=>{ if(b.disabled) return; const on=!b.classList.contains('on'); b.classList.toggle('on',on); b.setAttribute('aria-checked',String(on)); fn&&fn(on); }; };
  sw('swDev',on=>{ dev=on; g('devBox').classList.toggle('open',on); sync(); val2(); }); sw('swMeta'); sw('swRew',on=>{ rew=on; g('launchPage').classList.toggle('rew-off',!on); sync(); val2(); });
  function loadLogo(file){ if(!file||!file.type.startsWith('image/')){ toast('Please choose an image file','x'); return; } if(file.size>1024*1024){ toast('Logo too big, max 1 MB','x'); return; }
    const img=new Image(); img.onload=()=>{ const c=document.createElement('canvas'); c.width=c.height=256; const x=c.getContext('2d'); const s=Math.min(img.width,img.height); x.drawImage(img,(img.width-s)/2,(img.height-s)/2,s,s,0,0,256,256); logoURL=c.toDataURL('image/webp',0.85); sync(); }; img.src=URL.createObjectURL(file); }
  g('fLogo').addEventListener('change',e=>loadLogo(e.target.files[0])); const dz=g('drop'); ['dragenter','dragover'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault(); dz.style.borderColor='var(--color-accent)';})); ['dragleave','drop'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault(); dz.style.borderColor='';})); dz.addEventListener('drop',e=>loadLogo(e.dataTransfer.files[0]));
  const cta=g('deploy'); const setCta=()=>{ cta.textContent=W.connected?'Launch token':'Connect Wallet'; }; setCta(); document.addEventListener('wallet-change',setCta);
  cta.onclick=()=>{ if(!W.connected){ openConnect(); const t=setInterval(()=>{ if(W.connected){ clearInterval(t); setCta(); } },500); return; } if(!val1()||!val2()){ toast('Fix the highlighted fields','x'); $('main').scrollTo({top:0,behavior:'smooth'}); return; } if(PRE){ toast('Launches open when the contracts go live on Ink'); return; } cta.disabled=true; cta.textContent='Confirm in wallet…'; setTimeout(()=>{ cta.textContent='Deploying…'; },900);
    setTimeout(()=>{ cta.disabled=false; setCta(); $('.lf-grid').classList.add('hidden'); g('doneBox').classList.remove('hidden'); toast((g('fName').value||'Token')+' deployed on Ink'); $('main').scrollTo({top:0,behavior:'smooth'}); },2200); };
  g('shareX').onclick=()=>{ const t=g('fTick').value.trim().toUpperCase(); open('https://x.com/intent/tweet?text='+encodeURIComponent('$'+t+' is live on Inkypump (Ink), paired with '+pair+'. LP locked forever.'+(rew?' Holders earn '+(basket.join(' + ')||pair)+' on every trade.':''))); };
  sync();
}

/* ======================= LEADERBOARD ======================= */
function initBoard(){
  const pool=PRE?0:0.93; const payout=i=>i<5?pool*LB_TIER[i]/100:0;
  function draw(kind){ const rows=kind==='pnl'?LB_PNL:LB_VOL; setTab('#btabs [data-board]',$(`#btabs [data-board="${kind}"]`));
    if(!rows.length){ $('#podium').innerHTML=''; $('#bth').innerHTML=''; $('#btb').innerHTML=''; $('#bmob').innerHTML=''; $('#podium').insertAdjacentHTML('beforeend','<div class="o-feed-empty col-span-full">'+emptyBox('No trades yet','Epoch 1 starts when the first pool opens. Every trade on any coin counts.',null,null,true)+'</div>'); return; }
    $('#podium').innerHTML=rows.slice(0,3).map((r,i)=>`<div class="flex items-center gap-3 rounded-2xl px-4 py-3 ${r[2]?'border border-accent/20 bg-accent/10':'bg-bg-input'}">${rank(i)}<div class="min-w-0 flex-1"><div class="flex items-center gap-2"><span class="truncate font-mono text-sm font-semibold text-text-primary">${r[0]}</span>${r[2]?'<span class="inline-flex h-5 items-center rounded-full bg-accent px-2 text-[11px] font-semibold text-accent-ink">YOU</span>':''}</div><div class="mt-1 text-xs text-text-muted">${kind==='pnl'?'realized PnL':'fees paid · volume '+(r[1]*50).toFixed(0)+' ETH'}</div></div><div class="shrink-0 text-right"><div class="text-[15px] font-semibold tabular-nums ${kind==='pnl'?'text-success':'text-text-primary'}">${kind==='pnl'?'+':''}${r[1].toFixed(2)} ETH</div><div class="mt-0.5 text-xs tabular-nums text-text-muted">payout ${payout(i).toFixed(3)} ETH</div></div></div>`).join('');
    const th=(t,w,a)=>`<th class="h-12 whitespace-nowrap bg-bg-input px-3 align-middle font-normal first:rounded-l-2xl first:pl-4 last:rounded-r-2xl last:pr-5 w-[${w}] text-${a}">${t}</th>`;
    $('#bth').innerHTML=th('#','7%','left')+th('Wallet','15%','left')+th(kind==='pnl'?'Realized PnL':'Fees paid','14%','right')+th('Trades','12%','right')+th('Best token','15%','right')+th('Payout','13%','right');
    $('#btb').innerHTML=rows.map((r,i)=>{ const x=TOK[i%TOK.length]; return `<tr class="h-[4.5rem] text-text-primary${r[2]?' bg-accent/10':''}${i>=5?' opacity-60':''}">${tdiv('whitespace-nowrap px-4 py-3 align-middle',rank(i,true))}${tdiv('px-4 py-3 align-middle',wlink(r[0])+(r[2]?tagS('YOU'):''))}${tdiv('px-4 py-3 align-middle text-right tabular-nums','<span class="block font-medium '+(kind==='pnl'?'text-success':'text-text-primary')+'">'+(kind==='pnl'?'+':'')+r[1].toFixed(2)+' ETH</span>')}${tdiv('px-4 py-3 align-middle text-right tabular-nums',cellR(String(40+Math.floor(rnd()*300))))}${tdiv('px-4 py-3 align-middle text-right','<span class="inline-flex items-center justify-end gap-2">'+tokAv(x,'size-6 text-[10px]')+'<span class="font-medium">$'+x.t+'</span></span>')}${tdiv('px-4 py-3 align-middle text-right tabular-nums',i<5?cellR(payout(i).toFixed(3)+' ETH'):'<span class="block text-text-muted">—</span>')}</tr>`; }).join('')+`<tr><td colspan="6" class="px-4 py-4 text-center text-xs text-text-muted">only the top 5 are paid · #6 needs +0.15 ETH to get in</td></tr>`;
    $('#bmob').innerHTML=rows.map((r,i)=>`<div class="flex items-center gap-3 border-b border-border-default py-3 last:border-b-0${i>=5?' opacity-60':''}">${rank(i,true)}<div class="min-w-0 flex-1"><div class="truncate font-mono text-sm font-semibold text-text-primary">${r[0]}${r[2]?' <span class="text-accent">· you</span>':''}</div><div class="mt-0.5 text-xs text-text-muted">${40+Math.floor(rnd()*300)} trades · best $${TOK[i%TOK.length].t}</div></div><div class="shrink-0 text-right"><div class="text-sm font-semibold tabular-nums ${kind==='pnl'?'text-success':'text-text-primary'}">${kind==='pnl'?'+':''}${r[1].toFixed(2)} ETH</div><div class="mt-0.5 text-xs text-text-muted">${i<5?'payout '+payout(i).toFixed(3)+' ETH':'—'}</div></div></div>`).join(''); }
  $$('#btabs [data-board]').forEach(b=>b.onclick=()=>draw(b.dataset.board)); draw('pnl');
  if(PRE){ $('#cd').textContent='At launch'; }
  let ends=LB_ENDS; if(!PRE) setInterval(()=>{ ends--; $('#cd').textContent=Math.floor(ends/86400)+'d '+Math.floor(ends%86400/3600)+'h '+Math.floor(ends%3600/60)+'m'; },1000);
  boardYou();
}
let YOU_HTML=null;
function boardYou(){ const y=$('#youCard'); if(!y) return; if(YOU_HTML===null) YOU_HTML=y.innerHTML; else { y.innerHTML=YOU_HTML; y.style.cursor=''; y.onclick=null; }
  if(W.connected&&PRE){ y.innerHTML='<div class="flex h-7 items-center"><div class="text-lg font-semibold text-text-primary">No trades yet</div></div><div class="mt-0.5 text-xs font-medium text-accent">Your rank appears after your first trade</div>'; }
  if(!W.connected){ y.innerHTML='<div class="flex h-7 items-center"><div class="text-lg font-semibold text-text-primary">Connect to see your rank</div></div><div class="mt-0.5 text-xs font-medium text-accent">Every trade counts, wherever you trade</div>'; y.style.cursor='pointer'; y.onclick=openConnect; }
}

/* ======================= PROFILE ======================= */
let PROFILE_HTML=null;
function initProfile(){
  { const pg=$('#profilePage'); if(PROFILE_HTML===null) PROFILE_HTML=pg.innerHTML; else pg.innerHTML=PROFILE_HTML; }
  if(!W.connected){ const pg=$('#profilePage'); pg.innerHTML=`<div class="o-empty"><div class="ic">${ic('wallet')}</div><h2>Connect your wallet</h2><p>See your holdings, stock rewards, creator fees and leaderboard payouts in one place.</p><button id="pc">Connect Wallet</button></div>`; $('#pc').onclick=openConnect; return; }
  const H=[{t:'MOGCAT',n:'Mogcat',c:'#f2a93b',bal:2104320,px:0.000927,avg:0.000352,earned:38.4,pend:21.9},{t:'CPEPE',n:'Cold Pepe',c:'#7fe3d1',bal:180400,px:0.00241,avg:0.00263,earned:12.1,pend:9.3},{t:'WEN',n:'Wen Lambo',c:'#b8c6ff',bal:910000,px:0.000412,avg:0.000301,earned:14.6,pend:8.1},{t:'GRASS',n:'Touch Grass',c:'#a3e68a',bal:52000,px:0.000288,avg:0.000330,earned:2.2,pend:1.9}];
  // header follows the connected wallet; nothing is sampled
  { const a=W.address, g=id=>document.getElementById(id); { const av=g('pfAv'); const wrap=av.parentElement; wrap.style.background=''; wrap.innerHTML=window.walletAvatar?walletAvatar(a,64).replace('width="64" height="64"','width="100%" height="100%"'):'<span class="absolute inset-0 flex items-center justify-center rounded-md font-bold text-white">'+a.slice(2,4).toUpperCase()+'</span>'; } g('pfAddrT').textContent=W.short; g('pfAddr').dataset.copy=a;
    if(PRE){ g('pfTags').innerHTML='<span class="inline-flex h-6 items-center gap-1.5 rounded-full px-2.5 text-xs font-semibold leading-none md:text-[11px] bg-bg-input text-text-secondary">Ink</span>'; g('pfTotal').textContent='$0.00'; const ts=g('pfTotalSub'); ts.textContent='No trades yet'; ts.className=ts.className.replace('text-success','text-text-muted'); g('pfRew').textContent='$0.00'; g('pfRewSub').textContent='across 0 coins'; g('claimAll').style.display='none';
      // every other stat block in the strip: zero value, muted sub line
      $$('#profilePage .items-stretch > div').forEach(bx=>{ const v=bx.querySelector('.text-\\[26px\\]'), s=bx.querySelector('.font-mono'); if(!v||v.id) return; const t=v.textContent.trim(); v.textContent=t.includes('ETH')?'0 ETH':t.startsWith('$')?'$0.00':t.startsWith('#')?'—':t.startsWith('+')||t.startsWith('-')?'$0.00':'0'; v.className=v.className.replace('text-success','text-text-primary').replace('text-error','text-text-primary'); if(s){ s.textContent='No trades yet'; s.className=s.className.replace('text-success','text-text-muted').replace('text-error','text-text-muted'); } }); } }
  if(PRE){ const em=t=>'<div class="o-feed-empty">'+emptyBox(t,'Rewards, holdings and payouts show up here once you trade.',null,null,true)+'</div>';
    $('#rewards').innerHTML=em('Nothing to claim yet'); $('#htb').innerHTML=''; $('#hmob').innerHTML=em('No holdings yet'); $('#ctb').innerHTML=''; $('#cmob').innerHTML=em('No tokens created yet'); $('#act').innerHTML=em('No activity yet');
    $$('#ptabs [data-ptab]').forEach(b=>b.onclick=()=>{ setTab('#ptabs [data-ptab]',b); $$('#ppanes [data-ppane]').forEach(x=>x.classList.toggle('hidden',x.dataset.ppane!==b.dataset.ptab)); });
    $('#claimAll').onclick=()=>toast('Nothing to claim yet'); return; }
  const bk=t=>BASKETS[t]||['SPYx'];
  const rrow=(av,title,sub,val,btns)=>`<div class="flex min-w-0 items-center gap-3 border-b border-border-default px-4 py-3 last:border-b-0 hover:bg-bg-elevated">${av}<div class="min-w-0 flex-1"><div class="truncate text-sm font-semibold text-text-primary">${title}</div><div class="mt-1 truncate text-xs text-text-muted">${sub}</div></div><div class="hidden shrink-0 text-right sm:block"><div class="text-sm font-semibold tabular-nums text-success">${val}</div></div><div class="flex shrink-0 gap-1.5">${btns}</div></div>`;
  const pb=(t,msg,pri)=>`<button class="inline-flex h-8 cursor-pointer items-center gap-1.5 rounded-full px-3 text-xs font-semibold transition-colors ${pri?'bg-accent text-accent-ink hover:bg-accent-hover':'bg-bg-elevated text-text-primary hover:bg-bg-selector-hover'}" data-toast="${msg}">${t}</button>`;
  $('#rewards').innerHTML=H.map(h=>rrow(tokAv(h,'size-9 text-sm'),h.n+' · $'+h.pend.toFixed(2)+' pending','paid in '+bk(h.t).join(' · ')+' · lifetime $'+h.earned.toFixed(2),'$'+h.pend.toFixed(2),pb('Claim','Claimed $'+h.pend.toFixed(2)+' in '+bk(h.t).join(', '),1)+pb('as ETH','Claimed as ETH')))
    +rrow(`<span class="flex size-9 shrink-0 items-center justify-center rounded-md bg-bg-elevated text-text-primary">${ic('coins')}</span>`,'Creator fees · Mogcat','0.7% of $1.21M 24h volume · lifetime 9.84 ETH','0.22 ETH',pb('Claim','Claimed 0.22 ETH',1))
    +rrow(`<span class="flex size-9 shrink-0 items-center justify-center rounded-md bg-bg-elevated text-text-primary">${ic('trophy')}</span>`,'Leaderboard · epoch 30','#2 PnL last epoch · 25% of 1.07 ETH','0.27 ETH',pb('Claim','Claimed 0.27 ETH',1));
  $('#htb').innerHTML=H.map(h=>{ const v=h.bal*h.px, p=(h.px/h.avg-1)*100; return `<tr class="h-[4.5rem] cursor-pointer text-text-primary hover:bg-bg-elevated" onclick="location.href='token.html'">${tdiv('px-4 py-3 align-middle','<span class="flex items-center gap-3">'+tokAv(h,'size-9 text-sm')+'<span class="min-w-0"><span class="block truncate text-sm font-bold">'+h.t+'</span><span class="block truncate text-xs text-text-muted">'+h.n+'</span></span></span>')}${tdiv('px-4 py-3 align-middle text-right tabular-nums',cellR(fmtAmt(h.bal)))}${tdiv('px-4 py-3 align-middle text-right tabular-nums',cellR(fmtUsd(v),(v/ETH).toFixed(3)+' ETH'))}${tdiv('px-4 py-3 align-middle text-right tabular-nums',cellR('$'+fmtPrice(h.avg)))}${tdiv('px-4 py-3 align-middle text-right tabular-nums','<span class="block font-medium '+(p>=0?'text-success':'text-error')+'">'+(p>=0?'+':'')+p.toFixed(1)+'%</span>')}${tdiv('px-4 py-3 align-middle text-right','<span class="inline-flex justify-end gap-1">'+bk(h.t).map(s=>stockAv(s,'size-5 text-[9px]')).join('')+'</span>')}${tdiv('px-4 py-3 align-middle text-right tabular-nums','<span class="block font-medium text-success">$'+h.pend.toFixed(2)+'</span>')}${tdiv('px-4 py-3 align-middle text-right','<span class="inline-flex gap-1" onclick="event.stopPropagation()">'+pb('50%','Sold 50% '+h.t)+pb('100%','Sold all '+h.t)+'</span>')}</tr>`; }).join('');
  $('#hmob').innerHTML=H.map(h=>{ const v=h.bal*h.px,p=(h.px/h.avg-1)*100; return `<a class="flex items-center gap-3 border-b border-border-default py-3.5 last:border-b-0" href="token.html">${tokAv(h,'size-11 text-sm')}<div class="min-w-0 flex-1"><div class="flex min-w-0 items-center gap-2"><span class="truncate text-sm font-bold text-text-primary">${h.t}</span><span class="truncate text-sm font-medium text-text-muted">${h.n}</span></div><div class="mt-1 flex items-center gap-1.5 text-[13px] leading-none text-text-muted"><span>${fmtAmt(h.bal)}</span><span class="text-text-disabled">·</span><span class="text-success">$${h.pend.toFixed(2)} pending</span></div></div><div class="shrink-0 text-right"><div class="text-[15px] font-medium tabular-nums text-text-primary">${fmtUsd(v)}</div><div class="mt-0.5 text-xs tabular-nums ${p>=0?'text-success':'text-error'}">${p>=0?'+':''}${p.toFixed(1)}%</div></div></a>`; }).join('');
  const x=TOK[0];
  $('#ctb').innerHTML=`<tr class="h-[4.5rem] cursor-pointer text-text-primary hover:bg-bg-elevated" onclick="location.href='token.html'">${tdiv('px-4 py-3 align-middle','<span class="flex items-center gap-3">'+tokAv(x,'size-9 text-sm')+'<span class="min-w-0"><span class="block truncate text-sm font-bold">'+x.t+'</span><span class="block truncate text-xs text-text-muted">'+x.n+'</span></span></span>')}${tdiv('px-4 py-3 align-middle text-right tabular-nums',cellR(fmtUsd(x.mc)))}${tdiv('px-4 py-3 align-middle text-right tabular-nums',cellR(fmtUsd(x.vol)))}${tdiv('px-4 py-3 align-middle text-right tabular-nums',cellR(x.h.toLocaleString()))}${tdiv('px-4 py-3 align-middle text-right tabular-nums',cellR('$53.8K','22.11 ETH lifetime'))}${tdiv('px-4 py-3 align-middle text-right tabular-nums','<span class="block font-medium text-success">0.22 ETH</span>')}${tdiv('px-4 py-3 align-middle text-right','<span class="inline-flex gap-1" onclick="event.stopPropagation()">'+pb('Claim','Claimed 0.22 ETH',1)+pb('Edit','Metadata editor opens in the live build')+'</span>')}</tr>`;
  $('#cmob').innerHTML=`<a class="flex items-center gap-3 py-3.5" href="token.html">${tokAv(x,'size-11 text-sm')}<div class="min-w-0 flex-1"><div class="text-sm font-bold text-text-primary">${x.t}</div><div class="mt-1 text-[13px] leading-none text-text-muted">${fmtUsd(x.mc)} mcap · ${x.h.toLocaleString()} holders</div></div><div class="shrink-0 text-right"><div class="text-[15px] font-medium text-success">0.22 ETH</div><div class="mt-0.5 text-xs text-text-muted">claimable</div></div></a>`;
  const ACT=[['4s ago','Buy','0.1 ETH → 239.1K MOGCAT','text-success'],['2h ago','Claim','$18.40 in NVDAx + SPYx + TSLAx + MSTRx · Mogcat rewards','text-success'],['5h ago','Sell','50% WEN → 0.182 ETH · +0.06 realized','text-error'],['9h ago','Claim as ETH','0.004 ETH · Cold Pepe rewards','text-success'],['yesterday','Leaderboard','Epoch 30 · #2 PnL · 0.27 ETH','text-success'],['2d ago','Launch','Mogcat · $MOGCAT deployed · basket NVDAx SPYx TSLAx MSTRx','text-text-primary']];
  $('#act').innerHTML=ACT.map(a=>`<div class="flex items-center gap-3 border-b border-border-default py-3.5 last:border-b-0"><span class="w-[72px] shrink-0 text-xs text-text-muted">${a[0]}</span><div class="min-w-0 flex-1 text-sm"><span class="font-semibold ${a[3]}">${a[1]}</span> <span class="text-text-secondary">${a[2]}</span></div><a class="inline-flex text-text-muted hover:text-accent" href="https://explorer.inkonchain.com" target="_blank" rel="noopener noreferrer">${ic('ext','size-3.5')}</a></div>`).join('');
  $$('#ptabs [data-ptab]').forEach(b=>b.onclick=()=>{ setTab('#ptabs [data-ptab]',b); $$('#ppanes [data-ppane]').forEach(p=>p.classList.toggle('hidden',p.dataset.ppane!==b.dataset.ptab)); });
  $('#claimAll').onclick=()=>toast('Claimed $41.20 in stocks, 0.22 ETH creator fees and 0.27 ETH leaderboard payout');
  if(!W.connected){ const pg=$('#profilePage'); pg.innerHTML=`<div class="o-empty"><div class="ic">${ic('wallet')}</div><h2>Connect your wallet</h2><p>See your holdings, stock rewards, creator fees and leaderboard payouts in one place.</p><button id="pc">Connect Wallet</button></div>`; $('#pc').onclick=openConnect; return; }
}

/* ======================= DOCS ======================= */
function initDocs(){ const links=$$('#toc a'); const main=$('main'); const hs=links.map(a=>$(a.getAttribute('href'))); const io=new IntersectionObserver(es=>{ es.forEach(e=>{ if(e.isIntersecting) links.forEach(a=>a.classList.toggle('on',a.getAttribute('href')==='#'+e.target.id)); }); },{root:main,rootMargin:'-10% 0px -80% 0px'}); hs.forEach(h=>h&&io.observe(h));
  links.forEach(a=>a.onclick=e=>{ e.preventDefault(); const t=$(a.getAttribute('href')); if(t) main.scrollTo({top:t.offsetTop-24,behavior:'smooth'}); history.replaceState(null,'',a.getAttribute('href')); });
  if(location.hash){ const t=$(location.hash); if(t) setTimeout(()=>main.scrollTo({top:t.offsetTop-24}),50); } }

/* ======================= ADMIN ======================= */

document.addEventListener('DOMContentLoaded',()=>{ if($('#launchPage')) initLaunch(); if($('#boardPage')) initBoard(); if($('#profilePage')) initProfile(); if($('#docsPage')) initDocs();  });
document.addEventListener('wallet-change',()=>{ if($('#profilePage')) initProfile(); if($('#boardPage')) boardYou(); });
