const { chromium } = require('playwright');
const V = {
  N: ':root{--accent:#ff5a1f;--pair:#7a4cff;--pair-ink:#5b33e0;--pair-soft:#efe9ff;--bg:#f4f4f1;--bg-2:#ebebe6;--line:#e3e2dc;--line-2:#d2d0c8;--glow:rgba(255,90,31,.05)}.btn-primary,.nav .launch-cta,.nav .launch-cta.on,.wallet-btn.btn-primary{background:var(--ink)!important;color:var(--surface)!important;border:1.5px solid var(--ink);border-radius:10px;box-shadow:3px 3px 0 var(--accent);transition:transform .08s,box-shadow .08s}.btn-primary:hover,.nav .launch-cta:hover,.wallet-btn.btn-primary:hover{transform:translate(-1px,-1px);box-shadow:4px 4px 0 var(--accent)}.btn-primary:active,.nav .launch-cta:active{transform:translate(2px,2px);box-shadow:1px 1px 0 var(--accent)}.btn-up,.btn-down{border:1.5px solid var(--ink);box-shadow:3px 3px 0 var(--ink)}.btn-up[disabled],.btn-down[disabled]{opacity:.55}.chip.on{box-shadow:2px 2px 0 var(--accent)}.trade .seg button.on.buy,.trade .seg button.on.sell{box-shadow:inset 0 0 0 1.5px var(--ink)}',
  D: ':root{--bg:#e6f0ec;--bg-2:#d9e8e2;--surface:#fbfdfc;--surface-2:#f2f8f5;--hover:#e9f2ee;--ink:#0f2624;--ink-2:#2c4643;--muted:#5d7571;--faint:#8fa6a1;--line:#cfe1da;--line-2:#b9d1c8;--accent:#ff5a3c;--accent-soft:#ffe6e0;--pair:#0e7064;--pair-ink:#0b5d53;--pair-soft:#d3ece6;--glow:rgba(255,90,60,.06)}.btn-primary,.nav .launch-cta,.nav .launch-cta.on,.wallet-btn.btn-primary{background:var(--ink)!important;color:var(--surface)!important;border:1.5px solid var(--ink);border-radius:10px;box-shadow:3px 3px 0 var(--accent);transition:transform .08s,box-shadow .08s}.btn-primary:hover,.nav .launch-cta:hover,.wallet-btn.btn-primary:hover{transform:translate(-1px,-1px);box-shadow:4px 4px 0 var(--accent)}.btn-primary:active,.nav .launch-cta:active{transform:translate(2px,2px);box-shadow:1px 1px 0 var(--accent)}.btn-up,.btn-down{border:1.5px solid var(--ink);box-shadow:3px 3px 0 var(--ink)}.btn-up[disabled],.btn-down[disabled]{opacity:.55}.chip.on{box-shadow:2px 2px 0 var(--accent)}.trade .seg button.on.buy,.trade .seg button.on.sell{box-shadow:inset 0 0 0 1.5px var(--ink)}',
  G: ':root{--bg:#fbf0c4;--bg-2:#f5e5a6;--surface:#fffcf0;--surface-2:#fff7dc;--hover:#fbf2cf;--ink:#231a06;--ink-2:#45391c;--muted:#76694a;--faint:#a99b78;--line:#eedfa6;--line-2:#e2cf86;--accent:#ff3d1f;--accent-soft:#ffe1d8;--pair:#16603f;--pair-ink:#11502f;--pair-soft:#dcefdf;--glow:rgba(255,61,31,.05)}.btn-primary,.nav .launch-cta,.nav .launch-cta.on,.wallet-btn.btn-primary{background:var(--ink)!important;color:var(--surface)!important;border:1.5px solid var(--ink);border-radius:10px;box-shadow:3px 3px 0 var(--accent);transition:transform .08s,box-shadow .08s}.btn-primary:hover,.nav .launch-cta:hover,.wallet-btn.btn-primary:hover{transform:translate(-1px,-1px);box-shadow:4px 4px 0 var(--accent)}.btn-primary:active,.nav .launch-cta:active{transform:translate(2px,2px);box-shadow:1px 1px 0 var(--accent)}.btn-up,.btn-down{border:1.5px solid var(--ink);box-shadow:3px 3px 0 var(--ink)}.btn-up[disabled],.btn-down[disabled]{opacity:.55}.chip.on{box-shadow:2px 2px 0 var(--accent)}.trade .seg button.on.buy,.trade .seg button.on.sell{box-shadow:inset 0 0 0 1.5px var(--ink)}',
};
(async () => { const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--proxy-bypass-list=127.0.0.1;localhost', '--ignore-certificate-errors'] });
  for (const [k, css] of Object.entries(V)) { for (const [path, name, h] of [['/', 'home', 820], ['/coin/0x233ed4c8d248d6cf0a568f77a2a626e74f933fde', 'coin', 900]]) {
    const p = await b.newPage({ viewport: { width: 1440, height: h } }); await p.goto('http://127.0.0.1:8790' + path, { waitUntil: 'networkidle' }); await p.addStyleTag({ content: css }); await p.waitForTimeout(2500);
    await p.screenshot({ path: `../var-${k}-${name}.png` }); await p.close(); } }
  await b.close(); })();
