import { HardhatUserConfig } from "hardhat/config";
import "@nomicfoundation/hardhat-toolbox";
import * as dotenv from "dotenv";

dotenv.config();
// The platform deployer key lives in its own gitignored file, generated by
// scripts/generate-deployer.ts. It only signs deployments; all admin roles
// are handed to PLATFORM_ADMIN at deploy time.
dotenv.config({ path: ".env.deployer" });

// Robinhood Chain is an Arbitrum Orbit chain. Endpoints and the chain id are
// supplied through the environment so the same config serves testnet and
// mainnet as Robinhood publishes them.
const ROBINHOOD_RPC_URL = process.env.ROBINHOOD_RPC_URL ?? "";
const ROBINHOOD_CHAIN_ID = Number(process.env.ROBINHOOD_CHAIN_ID ?? 0);
const BLOCKSCOUT_URL = process.env.BLOCKSCOUT_URL ?? "";
const PRIVATE_KEY = process.env.PRIVATE_KEY;

const config: HardhatUserConfig = {
  solidity: {
    version: "0.8.26",
    settings: {
      optimizer: { enabled: true, runs: 400 },
      viaIR: true,
    },
  },
  networks: {
    hardhat: {
      allowUnlimitedContractSize: false,
      ...(process.env.FORK === "1" && ROBINHOOD_RPC_URL
        ? {
            forking: { url: ROBINHOOD_RPC_URL },
            chainId: ROBINHOOD_CHAIN_ID || undefined,
          }
        : {}),
    },
    ...(ROBINHOOD_RPC_URL
      ? {
          robinhood: {
            url: ROBINHOOD_RPC_URL,
            chainId: ROBINHOOD_CHAIN_ID || undefined,
            accounts: PRIVATE_KEY ? [PRIVATE_KEY] : [],
          },
        }
      : {}),
  },
  etherscan: {
    // Blockscout instances accept any non-empty API key string.
    apiKey: {
      robinhood: process.env.BLOCKSCOUT_API_KEY ?? "blockscout",
    },
    customChains: BLOCKSCOUT_URL
      ? [
          {
            network: "robinhood",
            chainId: ROBINHOOD_CHAIN_ID,
            urls: {
              apiURL: `${BLOCKSCOUT_URL.replace(/\/$/, "")}/api`,
              browserURL: BLOCKSCOUT_URL,
            },
          },
        ]
      : [],
  },
  sourcify: { enabled: false },
  mocha: { timeout: 120_000 },
};

export default config;
