// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

import {Test} from "forge-std/Test.sol";
import {ShieldedPool} from "../src/ShieldedPool.sol";
import {Verifier} from "../src/Verifier.sol";
import {AllowlistGate} from "../src/AllowlistGate.sol";
import {IHasher} from "../src/interfaces/IHasher.sol";
import {IVerifier} from "../src/interfaces/IVerifier.sol";
import {IComplianceGate} from "../src/interfaces/IComplianceGate.sol";

/// End-to-end test driven by a REAL Groth16 proof generated off-chain by
/// js/build-fixture.js (run js/build-circuit.sh then js/build-fixture.js first).
/// The on-chain Poseidon hasher is deployed from circomlibjs-generated bytecode
/// so its hashes match the circuit exactly.
contract ShieldedPoolTest is Test {
    uint256 constant DENOMINATION = 1 ether;
    uint32 constant LEVELS = 20;

    ShieldedPool pool;
    AllowlistGate gate;
    IHasher hasher;
    Verifier verifier;

    address owner = address(0xABCD);
    address depositor = address(0xBEEF);

    // fixture
    uint256 commitment;
    uint256 root;
    uint256 nullifierHash;
    address payable recipient;
    uint256[2] pA;
    uint256[2][2] pB;
    uint256[2] pC;

    function setUp() public {
        hasher = IHasher(_deployHasher());

        verifier = new Verifier();
        gate = new AllowlistGate(owner);

        pool = new ShieldedPool(
            IVerifier(address(verifier)),
            hasher,
            DENOMINATION,
            LEVELS,
            IComplianceGate(address(gate)),
            owner
        );

        vm.prank(owner);
        gate.setAllowed(depositor, true);

        _loadFixture();
    }

    function test_DepositThenWithdraw() public {
        // deposit
        vm.deal(depositor, DENOMINATION);
        vm.prank(depositor);
        pool.deposit{value: DENOMINATION}(commitment);

        // the freshly inserted root must be recognised
        assertTrue(pool.isKnownRoot(root), "root not known after deposit");
        assertEq(address(pool).balance, DENOMINATION);

        // withdraw to a fresh recipient using the real proof
        assertEq(recipient.balance, 0);
        pool.withdraw(pA, pB, pC, root, nullifierHash, recipient, payable(address(0)), 0, 0);

        assertEq(recipient.balance, DENOMINATION, "recipient not paid");
        assertEq(address(pool).balance, 0, "pool not drained");
        assertTrue(pool.isSpent(nullifierHash), "nullifier not marked spent");
    }

    function test_DoubleSpendReverts() public {
        vm.deal(depositor, DENOMINATION);
        vm.prank(depositor);
        pool.deposit{value: DENOMINATION}(commitment);

        pool.withdraw(pA, pB, pC, root, nullifierHash, recipient, payable(address(0)), 0, 0);

        vm.expectRevert("note spent");
        pool.withdraw(pA, pB, pC, root, nullifierHash, recipient, payable(address(0)), 0, 0);
    }

    function test_DepositRejectedWhenNotAllowed() public {
        address stranger = address(0x9999);
        vm.deal(stranger, DENOMINATION);
        vm.prank(stranger);
        vm.expectRevert("not allowed");
        pool.deposit{value: DENOMINATION}(commitment);
    }

    function test_WrongDenominationReverts() public {
        vm.deal(depositor, 2 ether);
        vm.prank(depositor);
        vm.expectRevert("wrong denomination");
        pool.deposit{value: 0.5 ether}(commitment);
    }

    function test_UnknownRootReverts() public {
        vm.deal(depositor, DENOMINATION);
        vm.prank(depositor);
        pool.deposit{value: DENOMINATION}(commitment);

        uint256 fakeRoot = root + 1;
        vm.expectRevert("unknown root");
        pool.withdraw(pA, pB, pC, fakeRoot, nullifierHash, recipient, payable(address(0)), 0, 0);
    }

    function test_TamperedProofReverts() public {
        vm.deal(depositor, DENOMINATION);
        vm.prank(depositor);
        pool.deposit{value: DENOMINATION}(commitment);

        // redirect to a different recipient -> public input mismatch -> bad proof
        address payable attacker = payable(address(0xDEAD));
        vm.expectRevert("bad proof");
        pool.withdraw(pA, pB, pC, root, nullifierHash, attacker, payable(address(0)), 0, 0);
    }

    function test_GatelessPoolAllowsAnyone() public {
        // pool with screening disabled
        ShieldedPool open = new ShieldedPool(
            IVerifier(address(verifier)), hasher, DENOMINATION, LEVELS, IComplianceGate(address(0)), owner
        );
        address anyone = address(0x1234);
        vm.deal(anyone, DENOMINATION);
        vm.prank(anyone);
        open.deposit{value: DENOMINATION}(commitment);
        assertTrue(open.isKnownRoot(open.getLastRoot()));
    }

    // --- helpers ---

    function _deployHasher() internal returns (address h) {
        bytes memory bytecode = vm.parseBytes(vm.trim(vm.readFile("build/PoseidonT3.bytecode")));
        assembly {
            h := create(0, add(bytecode, 0x20), mload(bytecode))
        }
        require(h != address(0), "hasher deploy failed");
    }

    function _loadFixture() internal {
        string memory j = vm.readFile("build/fixture.json");
        commitment = vm.parseJsonUint(j, ".commitment");
        root = vm.parseJsonUint(j, ".root");
        nullifierHash = vm.parseJsonUint(j, ".nullifierHash");
        recipient = payable(vm.parseJsonAddress(j, ".recipient"));

        uint256[] memory a = vm.parseJsonUintArray(j, ".pAflat");
        uint256[] memory b = vm.parseJsonUintArray(j, ".pBflat");
        uint256[] memory c = vm.parseJsonUintArray(j, ".pCflat");
        pA = [a[0], a[1]];
        pB = [[b[0], b[1]], [b[2], b[3]]];
        pC = [c[0], c[1]];
    }
}
